# cmd-poll.ps1 - ASCII only. FERNSTEUERUNG: holt Cloud-Befehle (Worker-Queue) alle paar Min + fuehrt aus.
# Leichtgewichtig: KEIN git, KEINE Analyse -> kein Lock, schnell. Du gibst Befehle von ueberall, PC fuehrt aus.
$ErrorActionPreference = "Continue"
$repo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
Set-Location $repo
# FIX 2026-06-21 (teuer): npm i (Stagehand) macht package.json dirty -> git pull --rebase scheitert -> Bot-Pushes
# kamen nie an (sah aus wie AVG-Block, war es aber NICHT). Vor jedem Lauf die npm-Aenderungen verwerfen:
git checkout -- package.json package-lock.json 2>$null
# PURE-AUTOMATION (User 2026-06-21 "fuer spaeter pure automation"): vor jedem Kampagne-Lauf die Keys laden
# (GROQ/GEMINI -> Stagehand-AI klickt selbst; Shopify-Creds) + Stagehand-Paket sicherstellen. Damit laeuft eine
# aus der Cloud gequeuete Kampagne vollautonom am PC, ohne dass der User einen Befehl tippt.
function Ensure-Campaign {
  if (Test-Path "$env:USERPROFILE\luxe-secrets.ps1") { . "$env:USERPROFILE\luxe-secrets.ps1" }
  if (-not (Test-Path "node_modules\@browserbasehq\stagehand")) { npm i @browserbasehq/stagehand --no-audit --no-fund 2>$null | Out-Null }
  git checkout -- package.json package-lock.json 2>$null   # npm-Dirt verwerfen -> Push am Befehlsende klappt
}
# SELBST-PULL + NEUSTART (FIX 2026-06-21 Timing-Falle): neuesten Code holen BEVOR Befehle laufen, damit
# NEUE Befehle/Scripts sofort erkannt werden (sonst verwirft die alte cmd-poll unbekannte Befehle). Aendert
# der Pull die cmd-poll.ps1 selbst -> EINMAL mit neuem Code neu starten. Vor dem Lock -> kein Konflikt.
if (-not ($args -contains '-reexec')) {
  $before = (git rev-parse HEAD 2>$null)
  git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null | Out-Null
  $after = (git rev-parse HEAD 2>$null)
  if ($before -and $after -and ($before -ne $after)) {
    # SMOKE-TEST + AUTO-ROLLBACK (Recherche 2026-06-21): bricht ein gepulltes node-Script syntaktisch,
    # zurueck auf last-good-SHA, damit ein kaputter Push den PC NIE lahmlegt.
    $bad = $false
    foreach ($s in @("automation/local/cmd-poll-helpers.check","automation/local/post-health.mjs","automation/local/tiktok-upload-browser.mjs","automation/lib/resilience.mjs")) {
      if ((Test-Path $s) -and ($s -like "*.mjs")) { node --check $s 2>$null; if ($LASTEXITCODE -ne 0) { $bad = $true } }
    }
    if ($bad) { git reset --hard $before 2>$null | Out-Null; "ROLLBACK $((Get-Date).ToString('o')): kaputter Pull -> zurueck auf $before" | Out-File -Append "reports\selfupdate-rollback.txt" }
    else { & powershell -ExecutionPolicy Bypass -File $PSCommandPath -reexec; exit }
  }
}
# HEARTBEAT (Recherche 2026-06-21): jeder Poll schreibt Lebenszeichen -> Cloud/Worker sieht ob PC laeuft.
try { @{ ts = (Get-Date).ToString("o"); task = "cmd-poll"; head = (git rev-parse --short HEAD 2>$null) } | ConvertTo-Json -Compress | Set-Content "reports\heartbeat.json" -EA SilentlyContinue } catch {}
# SINGLE-INSTANCE, aber STALE-TOLERANT (FIX 2026-06-20 v2 "PC immer aktiv, Queue waechst trotzdem"):
# Der alte Global-Mutex blockierte FUER IMMER, wenn ein Lauf an einem Browser/node-Aufruf haengen blieb
# (Lock nie freigegeben -> jeder neue Poll stieg sofort aus -> Kanal tot). Jetzt: Lock-DATEI mit Zeitstempel.
# Anti-Stacking-Lock. FIX 2026-06-30 (User „nächstes mal alles autonom"): 12 Min war ZU lang — CLOUD-AN ruft
# cmd-poll alle 2 Min, sequenziell (wartet auf Ende) -> der frische Lock liess den Poller fast jede Runde sofort
# aussteigen -> gequeuete Cloud-Befehle liefen nie autonom. 90 s = kein echtes Stapeln (CLOUD-AN ist synchron),
# aber der Poller arbeitet jetzt JEDE 2-Min-Runde -> Cloud-Befehle laufen autonom in ~2-4 Min.
$lock = Join-Path $env:TEMP "luxe-cmdpoll.lock"
if (Test-Path $lock) {
  $age = (Get-Date) - (Get-Item $lock).LastWriteTime
  if ($age.TotalSeconds -lt 90) { exit }   # frischer Lock (<90s) = laeuft noch -> raus
}                                            # sonst: uebernehmen
# HARTER SINGLE-INSTANCE-RIEGEL (User 2026-07-01 "10 mal gepostet"): globaler Named-Mutex wirkt maschinenweit,
# also auch wenn mehrere CLOUD-AN-Fenster ODER mehrere Repo-Kopien laufen. Zweite Instanz steigt sofort aus.
$global:LuxeMtx = New-Object System.Threading.Mutex($false, "Global\LuxeCmdPoll")
if (-not $global:LuxeMtx.WaitOne(500)) { Write-Host "cmd-poll laeuft bereits (Mutex) -> exit"; exit }
Set-Content -Path $lock -Value "$PID" -ErrorAction SilentlyContinue
$secrets = "$env:USERPROFILE\luxe-secrets.ps1"; if (Test-Path $secrets) { . $secrets }
$brave = "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
if (-not (Test-Path $brave)) { $brave = "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" }
function Ensure-Brave {
  $o = Get-NetTCPConnection -LocalPort 9222 -State Listen -EA SilentlyContinue
  if (-not $o -and (Test-Path $brave)) {
    Get-Process brave -EA SilentlyContinue | Stop-Process -Force -EA SilentlyContinue; Start-Sleep 3
    Start-Process $brave -ArgumentList "--remote-debugging-port=9222","--remote-allow-origins=*","--user-data-dir=$env:USERPROFILE\brave-agent"; Start-Sleep 18
  }
}
try {
  $cmds = @()
  # QUELLE 1: Cloudflare-Worker (drain) - kann ausfallen (Tageslimit/1101).
  try { $r = Invoke-RestMethod -Uri "https://luxe-poster.allengchour.workers.dev/?key=Abanaban192%2B&drain=1" -TimeoutSec 25; if ($r.commands) { foreach ($it in $r.commands) { $cmds += "$($it.cmd)" } } } catch { Write-Host "[worker] down (Cloudflare-Limit?) -> nutze git-Kanal" }
  # QUELLE 2: GIT-BEFEHLSKANAL (worker-unabhaengig, "immer ein Weg"): Cloud committet automation/local/cloud-commands.json
  # -> PC pullt + fuehrt neue Befehle aus (Dedup via lokalem done-file). Funktioniert auch wenn der Worker tot ist.
  git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null | Out-Null
  $doneFile = "automation/local/cloud-commands-done.txt"
  if (Test-Path "automation/local/cloud-commands.json") {
    try {
      $done = if (Test-Path $doneFile) { Get-Content $doneFile } else { @() }
      foreach ($g in (Get-Content "automation/local/cloud-commands.json" -Raw | ConvertFrom-Json)) {
        if ($done -notcontains "$($g.id)") { $cmds += "$($g.cmd)"; Add-Content $doneFile "$($g.id)"; Write-Host "[git-cmd] $($g.cmd) (id $($g.id))" }
      }
    } catch { Write-Host "[git-cmd] Lesefehler: $($_.Exception.Message)" }
  }
  if (-not $cmds -or $cmds.Count -eq 0) { exit }
  foreach ($c in $cmds) {
    Write-Host "[cmd] $c"; Ensure-Brave
    switch ($c) {
      "tiktok"       { if ($env:TT_ACCESS_TOKEN) { $env:TT_PRIVACY_LEVEL="DRAFT"; & node "automation/tiktok-autopost.mjs" } else { & node "automation/local/tiktok-upload-browser.mjs" } }
      "post"         { if ($env:TT_ACCESS_TOKEN) { $env:TT_PRIVACY_LEVEL="DRAFT"; & node "automation/tiktok-autopost.mjs" } else { & node "automation/local/tiktok-upload-browser.mjs" } }
      "tiktok-sound-diag" { $env:TIKTOK_SOUND_DIAG="1"; & node "automation/local/tiktok-upload-browser.mjs"; $env:TIKTOK_SOUND_DIAG=$null; git add -f reports/tiktok-sound-*.png reports/tiktok-last-run.json 2>$null; git commit -m "auto(tiktok-sound-diag): Commercial-Music-Library-UI Screenshots (kein Post)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "tiktok-sound" { $env:TIKTOK_WEB_SOUND="1"; & node "automation/local/tiktok-upload-browser.mjs"; $env:TIKTOK_WEB_SOUND=$null; git add -f reports/tiktok-sound-*.png reports/tiktok-last-run.json automation/local/tiktok-upload-done.txt 2>$null; git commit -m "auto(tiktok-sound): Reel mit TikTok Commercial-Music-Library gepostet" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "tiktok-api"   { $env:TT_PRIVACY_LEVEL="DRAFT"; & node "automation/tiktok-autopost.mjs" }
      "autobot"      { & powershell -ExecutionPolicy Bypass -File "automation/local/tiktok-autobot.ps1" }
      "giga"         { & powershell -ExecutionPolicy Bypass -File "automation/local/tiktok-giga-bot.ps1" }
      "tiktok-photo" { & node "automation/tiktok-photo-post.mjs" }
      "ig-delete"   { & node "automation/local/ig-delete-dupes.mjs"; git add automation/local/ig-delete-shots/* 2>$null; git commit -m "ig-delete screenshots" 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "ig-delete-papillon" { $env:PLATFORM="ig"; $env:MATCH="Armkette Papillon (butterfly bracelet on white knit)"; & node "automation/local/ig-delete-dupes.mjs" --go --n 2; git add -f automation/local/ig-delete-shots/* reports/ig-delete.json 2>$null; git commit -m "auto(ig-delete-papillon): Lauf (echtes Ergebnis in reports/ig-delete.json)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "ig-cover"    { & node "automation/local/ig-reel-cover.mjs"; git add -f automation/local/ig-cover-shots/* reports/ig-cover.json 2>$null; git commit -m "auto(ig-cover): Reel-Cover-Versuch + Screenshots" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "fb-check"    { & node "automation/local/fb-check.mjs"; git add -f automation/local/fb-check-shots/* reports/fb-check.json 2>$null; git commit -m "auto(fb-check): Facebook-Seite Screenshots + Dubletten-Check" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "tt-delete-hat" { $env:PLATFORM="tiktok"; $env:MATCH="a black wide-brim felt fedora hat on white background (Fedora/Filzhut Montana)"; & node "automation/local/tiktok-delete-dupes.mjs" --go --n 2; git add -f automation/local/tiktok-delete-shots/* reports/tiktok-delete.json 2>$null; git commit -m "auto(tt-delete-hat): Lauf (echtes Ergebnis in reports/tiktok-delete.json)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "tt-delete-sneaker" { $env:PLATFORM="tiktok"; $env:MATCH="a white leather sneaker with a stripe and beige sole (weisser Sneaker Marco)"; & node "automation/local/tiktok-delete-dupes.mjs" --go --n 1; git add -f automation/local/tiktok-delete-shots/* reports/tiktok-delete.json 2>$null; git commit -m "auto(tt-delete-sneaker): Lauf (echtes Ergebnis in reports/tiktok-delete.json)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "ads-setup"   { & node "automation/local/tiktok-ads-setup.mjs"; git add -f automation/local/tiktok-ads-shots/* reports/tiktok-ads-setup.json 2>$null; git commit -m "auto(ads-setup): TikTok-Ads-Onboarding selbst ausgefüllt (stoppt vor Karte) + Screenshots" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "tiktok-delete-dry" { $env:PLATFORM="tiktok"; $env:MATCH="a man or men's clothing (Herren)"; & node "automation/local/tiktok-delete-dupes.mjs" --n 3; git add -f automation/local/tiktok-delete-shots/* reports/tiktok-delete.json 2>$null; git commit -m "auto(tiktok-delete-dry): Herren-Video-Kandidaten Screenshots (kein Löschen)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "konto-analyse" { & node "automation/local/tiktok-accounts-analyze.mjs"; git add -f automation/local/account-shots/* reports/tiktok-accounts.json 2>$null; git commit -m "auto(konto): TikTok-Konten-Analyse + Screenshots" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "post-health" { & node "automation/local/post-health.mjs"; git add -f reports/post-health.json reports/tiktok-last-run.json 2>$null; git commit -m "auto(health): Posting-Live-Check (gepostet/doppel/Fehler)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "profil"      { & node "automation/local/social-profile-update.mjs"; git add -f automation/local/profile-shots/* reports/profile-update.json 2>$null; git commit -m "auto(profil): IG+TikTok Profi-Bio + Screenshots" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "markt-capture" { & node "automation/local/marketplace-capture.mjs"; git add -f automation/local/marketplace-shots/* reports/marketplace-capture.json 2>$null; git commit -m "auto(markt): tutti/anibis/ricardo Inbox+Profil Screenshots" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "ai-test"     { & node "automation/local/ai-browser-test.mjs"; git add -f reports/ai-browser-test.json 2>$null; git commit -m "auto(ai-test): Stagehand-Installation verifiziert" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "markt-profil" { & node "automation/local/marketplace-profile.mjs"; git add -f automation/local/marketplace-shots/* reports/marketplace-profile.json 2>$null; git commit -m "auto(markt-profil): tutti/anibis/ricardo Profil + Screenshots" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "trust-fix"   { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/fix_trust_consistency.mjs" }
      "set-prices"  { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/set_trikot_prices.mjs" 2>&1 | Tee-Object -FilePath reports/set-prices.log | Select-Object -Last 6; git add -f reports/set-prices.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(set-prices): WM-Trikot-Preise gesetzt (perso 59.90 / blank 49.90)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "order-1004"  { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; $env:ORDER_NAME="1004"; & node "automation/order_lookup.mjs" 2>&1 | Select-Object -Last 20; $env:ORDER_NAME=$null; git add -f reports/order-1004.txt automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(order-1004): sendungs-/status-abfrage bestellung 1004" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "order-1005"  { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; $env:ORDER_NAME="1005"; & node "automation/order_lookup.mjs" 2>&1 | Select-Object -Last 20; $env:ORDER_NAME=$null; git add -f reports/order-1005.txt automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(order-1005): sendungs-/status-abfrage bestellung 1005" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "fix-track-1004" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; $env:ORDER_NAME="1004"; $env:FORCE="1"; & node "automation/fix_tracking.mjs" 2>&1 | Select-Object -Last 12; $env:ORDER_NAME=$null; $env:FORCE=$null; git add -f reports/fix-tracking-1004.txt automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(fix-track-1004): tracking-link auf echte carrier-nummer (13-stellig) korrigiert" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "perso-dry"   { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/printful_perso_bridge.mjs" 2>&1 | Tee-Object -FilePath reports/perso-dry.log | Select-Object -Last 15; git add -f reports/perso-dry.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(perso-dry): DRY-Smoke-Test Perso-Bruecke (kein Geld, keine Order)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "perso-go"    { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; $env:GO="1"; & node "automation/printful_perso_bridge.mjs" 2>&1 | Tee-Object -FilePath reports/perso-go.log | Select-Object -Last 15; $env:GO=$null; git add -f reports/perso-go.log reports/perso-orders-done.json automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(perso-go): perso-trikot-orders als Printful-ENTWURF gestaged (confirm=0, keine Zahlung)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "klaviyo-track-dry" { & node "automation/local/klaviyo-tracking-port.mjs" 2>&1 | Select-Object -Last 8; git add -f automation/local/klaviyo-shots/* reports/klaviyo-track.txt automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(klaviyo-track-dry): integrations-status + screenshots (nichts geklickt)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "klaviyo-track-go" { $env:GO="1"; & node "automation/local/klaviyo-tracking-port.mjs" 2>&1 | Select-Object -Last 8; $env:GO=$null; git add -f automation/local/klaviyo-shots/* reports/klaviyo-track.txt automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(klaviyo-track-go): web-tracking/sync toggle geklickt" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "judgeme-dry" { & node "automation/local/judgeme-reviews-port.mjs" 2>&1 | Select-Object -Last 8; git add -f automation/local/judgeme-shots/* reports/judgeme.txt automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(judgeme-dry): judge.me-status + screenshots (nichts geklickt)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "judgeme-go" { $env:GO="1"; & node "automation/local/judgeme-reviews-port.mjs" 2>&1 | Select-Object -Last 8; $env:GO=$null; git add -f automation/local/judgeme-shots/* reports/judgeme.txt automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(judgeme-go): auto-bewertungs-anfrage aktiviert (ehrlich, kein fake-import)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "repoint-designer" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/repoint_designer.mjs" 2>&1 | Tee-Object -FilePath reports/repoint-designer.log | Select-Object -Last 15; git add -f reports/repoint-designer.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(repoint-designer): POD-Produkte auf Shopify-CDN-Designer umgestellt" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "upload-designer" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/upload_designer.mjs" 2>&1 | Tee-Object -FilePath reports/upload-designer.log | Select-Object -Last 15; git add -f reports/upload-designer.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(upload-designer): saubere designer.js auf Shopify-CDN hochgeladen" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "page-critique" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/page_critique.mjs" 2>&1 | Select-Object -Last 6; git add -f reports/page-critique.md automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(page-critique): Multi-KI-Kritik (Groq/Gemini/GPT) der Live-Seiten" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "rename-trikot" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/rename_trikot_generic.mjs" 2>&1 | Tee-Object -FilePath reports/rename-trikot.log | Select-Object -Last 8; git add -f reports/rename-trikot.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(rename-trikot): generisch (kein WM/World-Cup, recht+ehrlich)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "scrub-germany" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/scrub_germany.mjs" 2>&1 | Tee-Object -FilePath reports/scrub-germany.log | Select-Object -Last 8; git add -f reports/scrub-germany.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(scrub-germany): Deutschland/EU-versand raus (strikt CH)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "seo-page" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/create_seo_landing.mjs" 2>&1 | Tee-Object -FilePath reports/seo-page.log | Select-Object -Last 8; git add -f reports/seo-page.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(seo-page): Fan-Trikot-selbst-gestalten landingpage" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "seo-pages" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/create_seo_pages.mjs" 2>&1 | Tee-Object -FilePath reports/seo-pages.log | Select-Object -Last 10; git add -f reports/seo-pages.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(seo-pages): 6 kategorie-landingpages angelegt" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "seo-pages2" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/create_seo_pages_batch2.mjs" 2>&1 | Tee-Object -FilePath reports/seo-pages2.log | Select-Object -Last 12; git add -f reports/seo-pages2.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(seo-pages2): 8 weitere kategorie-landingpages (20-agenten-schwarm)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "seo-pages3" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/create_seo_pages_batch3.mjs" 2>&1 | Tee-Object -FilePath reports/seo-pages3.log | Select-Object -Last 10; git add -f reports/seo-pages3.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(seo-pages3): 4 weitere landingpages (ringe/ohrringe/makeup/smartwatches)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "blog-posts2" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/create_blog_posts_batch2.mjs" 2>&1 | Tee-Object -FilePath reports/blog-posts2.log | Select-Object -Last 10; git add -f reports/blog-posts2.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(blog-posts2): 3 weitere SEO-ratgeber (ringgroesse/uv400/muttertag)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "blog-posts" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/create_blog_posts.mjs" 2>&1 | Tee-Object -FilePath reports/blog-posts.log | Select-Object -Last 12; git add -f reports/blog-posts.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(blog-posts): 5 SEO-ratgeber-artikel angelegt (20-agenten-schwarm)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "set-trikot-imgs" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; $env:MOCKUPS="https://cdn.shopify.com/s/files/1/0943/6856/3585/files/all-over-print-recycled-unisex-sports-jersey-white-front-6a489d0533441_800x800.jpg,https://cdn.shopify.com/s/files/1/0943/6856/3585/files/all-over-print-recycled-unisex-sports-jersey-white-back-6a489d0533f59_800x800.jpg"; $env:REPLACE="1"; $env:PRODUCT_ID="gid://shopify/Product/15433948070273"; & node "automation/set_trikot_images.mjs" 2>&1 | Tee-Object -FilePath reports/set-trikot-imgs.log; $env:PRODUCT_ID="gid://shopify/Product/15447487480193"; & node "automation/set_trikot_images.mjs" 2>&1 | Tee-Object -FilePath reports/set-trikot-imgs.log -Append | Select-Object -Last 12; $env:MOCKUPS=$null; $env:REPLACE=$null; $env:PRODUCT_ID=$null; git add -f reports/set-trikot-imgs.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(set-trikot-imgs): echte kreuz-mockups als produktbilder (fake-cartoons raus)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "rename-wm-coll" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; & node "automation/rename_wm_collection.mjs" 2>&1 | Tee-Object -FilePath reports/rename-wm-coll.log | Select-Object -Last 8; git add -f reports/rename-wm-coll.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(rename-wm-coll): collection-titel generisch (kein WM)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "tt-delete-dry" { & node "automation/local/tiktok-delete-dupes.mjs"; git add -f automation/local/tiktok-delete-shots/* reports/tiktok-delete.json 2>$null; git commit -m "auto(tt-delete): DRY Dubletten-Vorschau" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "tt-delete-go" { & node "automation/local/tiktok-delete-dupes.mjs" --go --n 3; git add -f automation/local/tiktok-delete-shots/* reports/tiktok-delete.json 2>$null; git commit -m "auto(tt-delete): Lauf (echtes Ergebnis in reports/tiktok-delete.json)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "ig-delete-dry" { $env:PLATFORM="ig"; & node "automation/local/tiktok-delete-dupes.mjs"; $env:PLATFORM=$null; git add -f automation/local/ig-delete-shots/* reports/ig-delete.json 2>$null; git commit -m "auto(ig-delete): DRY Dubletten-Vorschau (AI)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "ig-delete-go" { $env:PLATFORM="ig"; & node "automation/local/tiktok-delete-dupes.mjs" --go --n 2; $env:PLATFORM=$null; git add -f automation/local/ig-delete-shots/* reports/ig-delete.json 2>$null; git commit -m "auto(ig-delete): Lauf (echtes Ergebnis in reports/ig-delete.json)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "fb-join"     { & node "automation/local/fb-groups.mjs" join; git add -f automation/local/fb-groups-shots/* automation/local/fb-groups-done.txt reports/fb-groups.json 2>$null; git commit -m "auto(fb-join): Gruppen beitreten (langsam)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "fb-group-post" { & node "automation/local/fb-groups.mjs" post; git add -f automation/local/fb-groups-shots/* automation/local/fb-groups-done.txt reports/fb-groups.json 2>$null; git commit -m "auto(fb-group-post): 1 nativer Post in Gruppe" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "sources"      { & node "automation/check-sources.mjs" --fix; git add -A 2>$null; git commit -m "auto(Quellen-Check): Dubletten bereinigt" 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "seo"          { Start-Process powershell -WindowStyle Hidden -ArgumentList '-ExecutionPolicy','Bypass','-Command',"`$env:MAX=200; node automation/seo_polish.mjs; git add -A; git commit -m auto-seo; git pull --rebase origin claude/luxestyle-product-CizQ6; git push origin claude/luxestyle-product-CizQ6" }
      "enrich"       { Start-Process powershell -WindowStyle Hidden -ArgumentList '-ExecutionPolicy','Bypass','-Command',"if(Test-Path `"`$env:USERPROFILE\luxe-secrets.ps1`"){ . `"`$env:USERPROFILE\luxe-secrets.ps1`" }; `$env:MAX=120; node automation/enrich_apparel_descriptions.mjs; git add -A; git commit -m auto-enrich; git pull --rebase origin claude/luxestyle-product-CizQ6; git push origin claude/luxestyle-product-CizQ6" }
      "feed"         { Start-Process powershell -WindowStyle Hidden -ArgumentList '-ExecutionPolicy','Bypass','-Command',"if(Test-Path `"`$env:USERPROFILE\luxe-secrets.ps1`"){ . `"`$env:USERPROFILE\luxe-secrets.ps1`" }; `$env:MAX=300; node automation/feed_polish.mjs; git add -A; git commit -m auto-feed; git pull --rebase origin claude/luxestyle-product-CizQ6; git push origin claude/luxestyle-product-CizQ6" }
      "shippingtext" { $env:MAX="500"; & node "automation/fix_shipping_text.mjs"; Remove-Item Env:MAX -EA SilentlyContinue }
      "follower"     { & node "automation/local/ch-follower-growth.mjs" }
      "engage"       { & node "automation/local/tiktok-bot.mjs" engage --cap 12 }
      "meta-dm"      { $env:MAX="10"; & node "automation/local/ig-dm-browser.mjs"; & node "automation/local/tiktok-dm-browser.mjs"; & node "automation/local/tiktok-bot.mjs" engage --cap 10; $env:MAX=$null; git add -f ig-dm-done.json tiktok-dm-done.json automation/local/ig-dm-shots/* automation/local/tiktok-dm-shots/* 2>$null; git commit -m "auto(meta-dm): IG+TikTok DMs + Kommentare beantwortet" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "analyse"      { & node "automation/local/tiktok-bot.mjs" analyze --max 80; & node "automation/tiktok-pixel-check.mjs" }
      "health"       { & node "automation/health-check.mjs"; git add reports/ 2>$null; git commit -m "auto(health): Provider/Key-Check" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "image-audit"  { Start-Process powershell -WindowStyle Hidden -ArgumentList '-ExecutionPolicy','Bypass','-Command',"`$env:MAX=300; node automation/image-audit.mjs; git add reports/; git commit -m auto-imageaudit; git pull --rebase origin claude/luxestyle-product-CizQ6; git push origin claude/luxestyle-product-CizQ6" }
      "cleanup"      { & powershell -ExecutionPolicy Bypass -File "automation/local/cleanup-storage.ps1" }
      "yt-learn"     { Start-Process powershell -WindowStyle Hidden -ArgumentList '-ExecutionPolicy','Bypass','-Command',"node automation/yt-learn.mjs; git add reports/; git commit -m auto-ytlearn; git pull --rebase origin claude/luxestyle-product-CizQ6; git push origin claude/luxestyle-product-CizQ6" }
      "tutti"        { $env:AUTO_PUBLISH="1"; & node "automation/local/tutti-post.mjs"; $env:AUTO_PUBLISH=$null }
      "anibis"       { $env:AUTO_PUBLISH="1"; & node "automation/local/anibis-post.mjs"; $env:AUTO_PUBLISH=$null }
      "campaign-dry" { Ensure-Campaign; $env:TT_OBJECTIVE="Traffic"; $env:TT_VIDEO="reels/seedance-wasserfest-sound.mp4"; $env:TT_LANDING="https://luxestyle.ch/discount/WELCOME10?redirect=/collections/wasserfester-schmuck"; $env:TT_ADTEXT="Bliebt das wirklich Gold? Wasserfeschte Edelstahl-Schmuck - lauft nid a, kei gruene Hut. -10% mit WELCOME10."; & node "automation/local/tiktok-campaign-port.mjs" --dry; $env:TT_OBJECTIVE=$null; $env:TT_VIDEO=$null; $env:TT_LANDING=$null; $env:TT_ADTEXT=$null; git add -f automation/local/campaign-shots/* reports/campaign-last-run.json 2>$null; git commit -m "auto(campaign-dry): sauberes Top-Ad (wasserfest) Screenshots" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "campaign-go"  { Ensure-Campaign; $env:AUTO_LAUNCH="1"; & node "automation/local/tiktok-campaign-port.mjs"; $env:AUTO_LAUNCH=$null; git add -f automation/local/campaign-shots/* reports/campaign-last-run.json 2>$null; git commit -m "auto(campaign-go): Screenshots zur Kontrolle" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "campaign-api-dry" { Ensure-Campaign; $env:DRY="1"; & node "automation/tiktok-campaign-api.mjs"; $env:DRY=$null; git add -f reports/campaign-api-last-run.json 2>$null; git commit -m "auto(campaign-api-dry): API-Lauf DRY (Budget-Cap-Check)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "campaign-api-go" { Ensure-Campaign; $env:DAILY_BUDGET="20"; $env:TOTAL_BUDGET="70"; & node "automation/tiktok-campaign-api.mjs"; $env:DAILY_BUDGET=$null; $env:TOTAL_BUDGET=$null; git add -f reports/campaign-api-last-run.json 2>$null; git commit -m "auto(campaign-api-go): Traffic-Kampagne via Marketing-API (70 CHF Cap)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "datasharing"    { Ensure-Campaign; & node "automation/local/shopify-datasharing.mjs"; git add -f automation/local/datasharing-shots/* reports/datasharing-last-run.json 2>$null; git commit -m "auto(datasharing): Datenfreigabe DRY" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "datasharing-go" { Ensure-Campaign; $env:AUTO_GO="1"; & node "automation/local/shopify-datasharing.mjs"; $env:AUTO_GO=$null; git add -f automation/local/datasharing-shots/* reports/datasharing-last-run.json 2>$null; git commit -m "auto(datasharing-go): Datenfreigabe Maximum gesetzt" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "storefront-audit" { Ensure-Campaign; & node "automation/local/storefront-audit.mjs"; git add -f automation/local/storefront-shots/* reports/storefront-audit.json 2>$null; git commit -m "auto(storefront-audit): jede Seite Screenshot+Vision" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "shopify-campaign"    { Ensure-Campaign; & node "automation/local/shopify-tiktok-campaign.mjs"; git add -f automation/local/shopify-campaign-shots/* reports/shopify-campaign-last-run.json 2>$null; git commit -m "auto(shopify-campaign): Shopify-TikTok Smart+ DRY Screenshots" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "shopify-campaign-go" { Ensure-Campaign; $env:AUTO_LAUNCH="1"; $env:TT_DAILY_BUDGET="10"; & node "automation/local/shopify-tiktok-campaign.mjs"; $env:AUTO_LAUNCH=$null; $env:TT_DAILY_BUDGET=$null; git add -f automation/local/shopify-campaign-shots/* reports/shopify-campaign-last-run.json 2>$null; git commit -m "auto(shopify-campaign-go): Smart+ Kampagne abgesendet" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "smartplus-dry" { Ensure-Campaign; if (-not (Test-Path "node_modules/playwright-core")) { Write-Host "installiere playwright-core ..."; npm i playwright-core --no-audit --no-fund 2>$null | Out-Null }; Write-Host "Brave mit --remote-allow-origins=* neu starten (WS-Fix erzwingen)..."; Get-Process brave -EA SilentlyContinue | Stop-Process -Force -EA SilentlyContinue; Start-Sleep 3; if (Test-Path $brave) { Start-Process $brave -ArgumentList "--remote-debugging-port=9222","--remote-allow-origins=*","--user-data-dir=$env:USERPROFILE\brave-agent","https://admin.shopify.com/store/luxestyle-ch/apps/tiktok-ads-2/ad_creation"; Start-Sleep 20 }; $env:CDP_HOST="127.0.0.1"; & node "automation/vps/smartplus-drive.mjs" 2>&1 | Out-File -Encoding utf8 reports/smartplus-drive.log; $env:CDP_HOST=$null; Write-Host "smartplus-dry fertig -> Trace + Log"; git add -f reports/smartplus-trace.txt reports/smartplus-shot.png reports/smartplus-drive.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(smartplus-dry): pure-playwright Smart+ DRY Trace+Log (kein Geld)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "smartplus-continue" { Ensure-Campaign; if (-not (Test-Path "node_modules/playwright-core")) { npm i playwright-core --no-audit --no-fund 2>$null | Out-Null }; Write-Host "An OFFENEN Brave anhaengen (KEIN Neustart) + Picker abschliessen..."; $env:CDP_HOST="127.0.0.1"; $env:CONTINUE="1"; & node "automation/vps/smartplus-drive.mjs" 2>&1 | Out-File -Encoding utf8 reports/smartplus-drive.log; $env:CDP_HOST=$null; $env:CONTINUE=$null; Write-Host "smartplus-continue fertig"; git add -f reports/smartplus-trace.txt reports/smartplus-shot.png reports/smartplus-drive.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(smartplus-continue): offenen Picker abgeschlossen (DRY, kein Geld)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "smartplus-go" { Ensure-Campaign; if (-not (Test-Path "node_modules/playwright-core")) { npm i playwright-core --no-audit --no-fund 2>$null | Out-Null }; Write-Host "GO: Formular fertigstellen + SENDEN (User-autorisiert, 30 CHF/Tag, geht in TikTok-Review)..."; $env:CDP_HOST="127.0.0.1"; $env:CONTINUE="1"; $env:GO="1"; & node "automation/vps/smartplus-drive.mjs" 2>&1 | Out-File -Encoding utf8 reports/smartplus-drive.log; $env:CDP_HOST=$null; $env:CONTINUE=$null; $env:GO=$null; Write-Host "smartplus-go fertig"; git add -f reports/smartplus-trace.txt reports/smartplus-shot.png reports/smartplus-drive.log automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(smartplus-go): Senden geklickt (User-GO, Review)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "tiktok-ads-learn" { Ensure-Campaign; if (-not (Test-Path "node_modules/playwright-core")) { npm i playwright-core --no-audit --no-fund 2>$null | Out-Null }; Write-Host "Bot lernt ads.tiktok.com (Struktur-Dump)..."; $env:CDP_HOST="127.0.0.1"; & node "automation/vps/tiktok-ads-learn.mjs" 2>&1 | Select-Object -Last 5; $env:CDP_HOST=$null; git add -f reports/tiktok-ads-learn.txt automation/local/cloud-commands-done.txt 2>$null; git commit -m "auto(tiktok-ads-learn): ads.tiktok.com Struktur gelernt (Dump)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "aurora-ai" { Ensure-Campaign; "$(if($env:FAL_KEY){'FAL=ok'}else{'FAL=MISSING'}) $(if($env:GEMINI_API_KEY){'GEMINI=ok'}else{'GEMINI=MISSING'}) $(if($env:ELEVENLABS_API_KEY){'ELEVEN=ok'}else{'ELEVEN=MISSING'}) @ $(Get-Date -Format o)" | Out-File -Encoding utf8 reports/aurora-ai-keys.txt; Get-Content reports/aurora-ai-keys.txt; git add -f reports/aurora-ai-keys.txt 2>$null; git commit -m "auto(aurora-ai-keys): Key-Status SOFORT (vor Generierung)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null; "" > reports/aurora-ai.log; $au1="https://cdn.shopify.com/s/files/1/0943/6856/3585/files/8d07fb80-6ec1-40b0-9c10-c47740fcc38c.jpg?v=1781380333"; $au2="https://cdn.shopify.com/s/files/1/0943/6856/3585/files/3d48340e-cc7f-4d18-8f74-cd2c8d463c9b.jpg?v=1781380333"; Write-Host "1) Nano Banana Hero-Bilder (toller Hintergrund)..."; node automation/nanobanana_lifestyle.mjs --image "$au1" --title "Aurora Moissanite Halskette" --style jewelry --out "social/ai-lifestyle/aurora-hero1.png" 2>&1 | tail -2; node automation/nanobanana_lifestyle.mjs --image "$au2" --title "Aurora Moissanite Halskette" --style jewelry --out "social/ai-lifestyle/aurora-hero2.png" 2>&1 | tail -2; Write-Host "2) Seedance: drehendes, glaenzendes Produkt..."; $prompt="luxury jewelry TV commercial, the necklace slowly rotates and turns on a turntable, dazzling sparkle and glossy light reflections on the colorful gemstones, elegant premium background with soft golden bokeh and aurora light glow, cinematic slow motion, photoreal, no text"; $srcs=@("social/ai-lifestyle/aurora-hero1.png","social/ai-lifestyle/aurora-hero2.png","$au1"); $i=1; foreach($s in $srcs){ if((Test-Path $s) -or ($s -match '^http')){ Write-Host "Seedance $i <- $s"; node automation/seedance_video.mjs --image "$s" --prompt "$prompt" --res 720p --dur 5 --ar 9:16 --out "reels/seedance-aurora-$i.mp4" 2>&1 | Tee-Object -FilePath reports/aurora-ai.log -Append | Select-Object -Last 4 }; $i++ }; Write-Host "3) ElevenLabs VO..."; $env:ELEVEN_VOICE_ID="Ljh056ZotKDfGTc2jGL4"; node automation/elevenlabs_tts.mjs "Aurora. Alle Farben des Nordlichts, in einer einzigen Kette. Echter Moissanit, Sterlingsilber, G R A zertifiziert, mit edler Geschenkbox. Jetzt bei LuxeStyle. Zehn Prozent mit dem Code Welcome zehn." "reports/aurora-vo.mp3" 2>&1 | tail -2; $env:ELEVEN_VOICE_ID=$null; git add -f reels/seedance-aurora-*.mp4 social/ai-lifestyle/aurora-hero*.png reports/aurora-vo.mp3 reports/aurora-ai-keys.txt reports/aurora-ai.log 2>$null; git commit -m "auto(aurora-ai): NanoBanana-Hero + Seedance drehendes Produkt + ElevenLabs VO" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "amore-veo" { Ensure-Campaign; Write-Host "Veo-Meisterwerk: Armband Amore (Gemini, Quota-Reset)..."; if (Test-Path "$env:USERPROFILE\luxe-secrets.ps1") { . "$env:USERPROFILE\luxe-secrets.ps1" }; node automation/veo_product_clip.mjs --image "https://cdn.shopify.com/s/files/1/0943/6856/3585/files/9d93cf1e-e3b1-4981-951e-caaf6644cdd3.jpg?v=1781585419" --prompt "luxury jewelry commercial, the gold heart charm bracelet slowly rotating on a white marble turntable, soft studio light, gentle glossy reflections, elegant minimal background, shallow depth of field, no text, no watermark, vertical 9:16" --aspect 9:16 --seconds 8 --out "reels/amore-raw.mp4" 2>&1 | Tee-Object -FilePath reports/amore-veo.log; git add -f reels/amore-raw.mp4 reports/amore-veo.log 2>$null; git commit -m "auto(amore-veo): Armband Amore Rohclip (Veo)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "veo-batch" { Ensure-Campaign; Write-Host "Veo-Batch: frische Rohclips (idempotent) rendern..."; if (Test-Path "$env:USERPROFILE\luxe-secrets.ps1") { . "$env:USERPROFILE\luxe-secrets.ps1" }; try { $bj = Get-Content "automation/local/veo-batch.json" -Raw | ConvertFrom-Json; foreach ($cl in $bj.clips) { if (Test-Path $cl.out) { Write-Host "skip: $($cl.out) existiert"; continue }; Write-Host "render (1/Veo) -> $($cl.out)"; node automation/veo_product_clip.mjs --image $cl.image --prompt $cl.prompt --aspect 9:16 --seconds 8 --out $cl.out 2>&1 | Tee-Object -FilePath reports/veo-batch.log -Append | Select-Object -Last 3; if (-not (Test-Path $cl.out)) { Write-Host "Veo leer -> (2/fal Seedance)"; node automation/seedance_video.mjs --image $cl.image --prompt $cl.prompt --res 720p --dur 8 --ar 9:16 --out $cl.out 2>&1 | Tee-Object -FilePath reports/veo-batch.log -Append | Select-Object -Last 3 }; if (Test-Path $cl.out) { Write-Host "OK: $($cl.out)" } else { Write-Host "FEHLGESCHLAGEN (Veo+fal leer): $($cl.out) - naechster Lauf versucht erneut" } } } catch { Write-Host "veo-batch Fehler: $_" }; git add -f reels/*-raw.mp4 reports/veo-batch.log 2>$null; git commit -m "auto(veo-batch): frische Veo-Rohclips gerendert" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "queue-videos" { Write-Host "Frische Clips auf Shopify-CDN laden + in Posting-Queue (video_queue.csv) -> build_queue -> IG/FB-Worker..."; if (Test-Path "$env:USERPROFILE\luxe-secrets.ps1") { . "$env:USERPROFILE\luxe-secrets.ps1" }; if (-not $env:SHOPIFY_SHOP) { $env:SHOPIFY_SHOP="au3j0y-hq.myshopify.com" }; "queue-videos Lauf $(Get-Date -Format o) SHOP=$(if($env:SHOPIFY_SHOP){'set'}else{'MISSING'}) CID=$(if($env:SHOPIFY_CLIENT_ID){'set'}else{'MISSING'})" | Out-File -Encoding utf8 reports/queue-videos.log; node automation/queue_veo_clips.mjs 2>&1 | Tee-Object -FilePath reports/queue-videos.log -Append | Select-Object -Last 25; git add -f social/video_queue.csv reports/queue-videos.log 2>$null; git commit -m "auto(queue-videos): frische Clips auf CDN + Posting-Queue (IG/FB)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "seedance-amore" { Ensure-Campaign; Write-Host "Seedance-Meisterwerk: Armband Amore (fal, Modell-Fallback)..."; if (Test-Path "$env:USERPROFILE\luxe-secrets.ps1") { . "$env:USERPROFILE\luxe-secrets.ps1" }; node automation/seedance_video.mjs --image "https://cdn.shopify.com/s/files/1/0943/6856/3585/files/9d93cf1e-e3b1-4981-951e-caaf6644cdd3.jpg?v=1781585419" --prompt "luxury jewelry commercial, the gold heart charm bracelet slowly rotating on a white marble turntable, soft studio light, gentle glossy reflections, elegant minimal background, shallow depth of field, photoreal, no text, no watermark, vertical 9:16" --res 720p --dur 5 --ar 9:16 --out "reels/seedance-amore.mp4" 2>&1 | Tee-Object -FilePath reports/seedance-amore.log; git add -f reels/seedance-amore.mp4 reports/seedance-amore.log 2>$null; git commit -m "auto(seedance-amore): Meisterwerk-Rohclip Armband Amore (fal)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "seedance-kette" { Ensure-Campaign; Write-Host "Seedance EIN Clip (Aurora-Kette) + voller Log..."; node automation/seedance_video.mjs --image "https://cdn.shopify.com/s/files/1/0943/6856/3585/files/3d48340e-cc7f-4d18-8f74-cd2c8d463c9b.jpg?v=1781380333" --prompt "luxury jewelry commercial, the rainbow gemstone necklace slowly rotating, dazzling sparkle and glossy reflections, elegant dark background with soft golden bokeh, cinematic slow motion, no text" --res 720p --dur 5 --ar 9:16 --out "reels/seedance-aurora-1.mp4" 2>&1 | Tee-Object -FilePath reports/seedance.log; git add -f reels/seedance-aurora-1.mp4 reports/seedance.log 2>$null; git commit -m "auto(seedance-kette): 1 Clip + voller Log (Diagnose)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "aurora-veo" { Ensure-Campaign; Write-Host "Veo (Gemini-Guthaben) drehendes Aurora-Ketten-Video..."; if (Test-Path "$env:USERPROFILE\luxe-secrets.ps1") { . "$env:USERPROFILE\luxe-secrets.ps1" }; node automation/veo_product_clip.mjs --image "https://cdn.shopify.com/s/files/1/0943/6856/3585/files/3d48340e-cc7f-4d18-8f74-cd2c8d463c9b.jpg?v=1781380333" --prompt "Cinematic luxury jewelry commercial. The rainbow-gemstone necklace slowly rotates and turns, dazzling sparkle and glossy light reflections across the colourful stones. Elegant dark background with soft golden bokeh and a subtle aurora light glow. Slow, smooth, stabilized motion. The necklace stays true to the reference image, same colours and design, no distortion. No text, no logo, no watermark. Vertical 9:16, high quality." --aspect 9:16 --seconds 8 --out "reels/veo-aurora.mp4" 2>&1 | Tee-Object -FilePath reports/veo-aurora.log; git add -f reels/veo-aurora.mp4 reports/veo-aurora.log 2>$null; git commit -m "auto(aurora-veo): Veo drehendes Aurora-Video (Gemini-Guthaben)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "aurora-voice" { Ensure-Campaign; Write-Host "Sexy Damen-Stimme (ElevenLabs) aufs Aurora-Video..."; & powershell -NoProfile -ExecutionPolicy Bypass -File "automation/local/aurora-voice.ps1" }
      "tiktok-bio" { Write-Host "TikTok-Bio setzen (Brave mit Debug-Flag neu starten)..."; if (-not (Test-Path "node_modules/playwright-core")) { npm i playwright-core --no-audit --no-fund 2>$null | Out-Null }; Get-Process brave -EA SilentlyContinue | Stop-Process -Force -EA SilentlyContinue; Start-Sleep 3; if (Test-Path $brave) { Start-Process $brave -ArgumentList "--remote-debugging-port=9222","--remote-allow-origins=*","--user-data-dir=$env:USERPROFILE\brave-agent","https://www.tiktok.com/@luxestyle.ch"; Start-Sleep 18 }; $env:CDP_HOST="127.0.0.1"; node automation/local/tiktok-bio.mjs 2>&1 | Select-Object -Last 5; $env:CDP_HOST=$null; git add -f reports/tiktok-bio.txt reports/tiktok-bio.png 2>$null; git commit -m "auto(tiktok-bio): Profil-Bio gesetzt (Trace+Screenshot)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "ads-read" { Ensure-Campaign; Write-Host "Ads-Dashboard aus PC-Brave lesen (Kampagnen-Zahlen)..."; if (Test-Path "$env:USERPROFILE\luxe-secrets.ps1") { . "$env:USERPROFILE\luxe-secrets.ps1" }; if (-not (Test-Path "node_modules/playwright-core")) { npm i playwright-core --no-audit --no-fund 2>$null | Out-Null }; $env:CDP_HOST="127.0.0.1"; node automation/vps/tiktok-ads-read.mjs 2>&1 | Tee-Object -FilePath reports/ads-read.log; $env:CDP_HOST=$null; git add -f reports/ads-read.log 2>$null; git commit -m "auto(ads-read): Kampagnen-Zahlen aus Ads-Dashboard gelesen" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "tiktok-stats" { Ensure-Campaign; Write-Host "TikTok Marketing-API Stats lesen (Token da)..."; if (Test-Path "$env:USERPROFILE\luxe-secrets.ps1") { . "$env:USERPROFILE\luxe-secrets.ps1" }; node automation/vps/tiktok-stats.mjs 2>&1 | Tee-Object -FilePath reports/tiktok-stats.log; git add -f reports/tiktok-stats.log 2>$null; git commit -m "auto(tiktok-stats): Marketing-API Stats gelesen -> luxe.tiktok_stats" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "fresh-veo" { Ensure-Campaign; Write-Host "Frische Clips via veo_product_clip (rotierende Stile, nicht immer Funkel)..."; if (Test-Path "$env:USERPROFILE\luxe-secrets.ps1") { . "$env:USERPROFILE\luxe-secrets.ps1" }; "" | Out-File -Encoding utf8 reports/fresh-veo.log; $prompts=@("elegant product commercial, soft natural daylight, gentle slow push-in, premium minimal background, calm and clean, no sparkle, no text, no watermark, vertical 9:16", "luxury product slowly rotating on a turntable, smooth glossy reflections, elegant dark background with soft bokeh, no text, no watermark, vertical 9:16", "premium product on a clean marble surface, soft studio light, subtle depth of field, refined minimal mood, no text, no watermark, vertical 9:16", "glamorous product with a few subtle sparkles, warm golden bokeh, cinematic gentle motion, no text, no watermark, vertical 9:16"); $imgs=Get-Content automation/good_products.csv | Select-Object -Skip 1 | Select-Object -First 4; $n=1; foreach($line in $imgs){ $url=($line -split ',')[1]; if($url -match '^http'){ $pr=$prompts[($n-1) % $prompts.Count]; node automation/veo_product_clip.mjs --image "$url" --prompt "$pr" --aspect 9:16 --seconds 8 --out "reels/fresh-veo-$n.mp4" 2>&1 | Tee-Object -FilePath reports/fresh-veo.log -Append; $n++ } }; git add -f reels/fresh-veo-*.mp4 reports/fresh-veo.log 2>$null; git commit -m "auto(fresh-veo): frische Clips (rotierende Stile)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "fresh-fal" { Ensure-Campaign; Write-Host "Frische Clips via fal/Seedance (guenstiges Guthaben verbrauchen)..."; if (Test-Path "$env:USERPROFILE\luxe-secrets.ps1") { . "$env:USERPROFILE\luxe-secrets.ps1" }; $prompts=@("elegant product, soft natural daylight, gentle slow push-in, clean minimal background, no sparkle, no text, vertical 9:16", "luxury product slowly rotating, smooth glossy reflections, elegant dark background with soft bokeh, no text, vertical 9:16", "premium product on clean marble, soft studio light, refined minimal mood, no text, vertical 9:16", "glamorous product, a few subtle sparkles, warm golden bokeh, cinematic, no text, vertical 9:16"); $imgs=Get-Content automation/good_products.csv | Select-Object -Skip 1 | Select-Object -First 6; $n=1; foreach($line in $imgs){ $url=($line -split ',')[1]; if($url -match '^http'){ $pr=$prompts[($n-1) % $prompts.Count]; node automation/seedance_video.mjs --image "$url" --prompt "$pr" --res 720p --dur 5 --ar 9:16 --out "reels/fresh-fal-$n.mp4" 2>&1 | Tee-Object -FilePath reports/fresh-fal.log -Append; $n++ } }; git add -f reels/fresh-fal-*.mp4 reports/fresh-fal.log 2>$null; git commit -m "auto(fresh-fal): frische Clips (fal-Guthaben)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "campaign-traffic" { Ensure-Campaign; $env:AUTO_LAUNCH="1"; $env:TT_OBJECTIVE="Traffic"; $env:TT_DAILY_BUDGET="20"; $env:TT_TOTAL_BUDGET="70"; $env:TT_VIDEO="reels/seedance-wasserfest-sound.mp4"; $env:TT_LANDING="https://luxestyle.ch/discount/WELCOME10?redirect=/collections/wasserfester-schmuck"; $env:TT_ADTEXT="Bliebt das wirklich Gold? Wasserfeschte Edelstahl-Schmuck - lauft nid a, kei gruene Hut. -10% mit WELCOME10."; "" | Out-File -Encoding ascii automation/local/tiktok-campaign-ledger.txt; & node "automation/local/tiktok-campaign-port.mjs"; $env:AUTO_LAUNCH=$null; $env:TT_OBJECTIVE=$null; $env:TT_DAILY_BUDGET=$null; $env:TT_TOTAL_BUDGET=$null; $env:TT_VIDEO=$null; $env:TT_LANDING=$null; $env:TT_ADTEXT=$null; git add -f automation/local/campaign-shots/* reports/campaign-last-run.json 2>$null; git commit -m "auto(campaign-traffic): sauberes Top-Ad wasserfest Screenshots" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "audit-ig"     { Ensure-Campaign; & node "automation/local/post-audit.mjs" --platform ig; git add -f automation/local/post-audit-shots/* reports/post-audit-ig.json 2>$null; git commit -m "auto(audit-ig): Post-Audit Vision (DRY)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "audit-tiktok" { Ensure-Campaign; & node "automation/local/post-audit.mjs" --platform tiktok; git add -f automation/local/post-audit-shots/* reports/post-audit-tiktok.json 2>$null; git commit -m "auto(audit-tiktok): Post-Audit Vision (DRY)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "audit-fb"     { Ensure-Campaign; & node "automation/local/post-audit.mjs" --platform fb; git add -f automation/local/post-audit-shots/* reports/post-audit-fb.json 2>$null; git commit -m "auto(audit-fb): Post-Audit Vision (DRY)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "audit-fb-go"  { Ensure-Campaign; & node "automation/local/post-audit.mjs" --platform fb --go; git add -f automation/local/post-audit-shots/* reports/post-audit-fb.json 2>$null; git commit -m "auto(audit-fb-go): Verstoesse geloescht" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "campaign-data" { Ensure-Campaign; $env:AUTO_LAUNCH="1"; $env:TT_EVENT="Add to Cart"; $env:TT_DAILY_BUDGET="10"; $env:TT_TOTAL_BUDGET="70"; "" | Out-File -Encoding ascii automation/local/tiktok-campaign-ledger.txt; & node "automation/local/tiktok-campaign-port.mjs"; $env:AUTO_LAUNCH=$null; $env:TT_EVENT=$null; $env:TT_DAILY_BUDGET=$null; $env:TT_TOTAL_BUDGET=$null; git add -f automation/local/campaign-shots/* reports/campaign-last-run.json 2>$null; git commit -m "auto(campaign-data): ATC-Daten-Kampagne Screenshots" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "bigbuy-beauty" { Start-Process powershell -ArgumentList '-ExecutionPolicy','Bypass','-Command','$env:ROOT_NAME=''cosmet'';$env:MAX=''12'';node dropship/bigbuy_import.mjs' -WindowStyle Hidden }
      "bigbuy-makeup" { Start-Process powershell -ArgumentList '-ExecutionPolicy','Bypass','-Command','$env:ROOT_NAME=''perfum'';$env:MAX=''12'';node dropship/bigbuy_import.mjs' -WindowStyle Hidden }
      "bigbuy-premium" { Start-Process powershell -ArgumentList '-ExecutionPolicy','Bypass','-File','automation/local/bigbuy-premium.ps1' -WindowStyle Hidden }
      "bigbuy-gaming" { Write-Host "BigBuy PS5/Gaming-Import (Elektronik-Wurzel + Name-Filter, gedrosselt)..."; Start-Process powershell -ArgumentList '-ExecutionPolicy','Bypass','-Command','$env:ROOT=''19653'';$env:NAME_FILTER=''ps5|playstation|dualsense|dualshock|nacon|gaming|controller|gamepad|headset'';$env:MAX=''12'';$env:SCAN_MAX=''400'';$env:MIN_COST_EUR=''5'';node dropship/bigbuy_import.mjs 2>&1 | Out-File -Encoding utf8 reports/bigbuy-gaming.log; git add -f dropship/bigbuy-imported-eans.txt reports/bigbuy-gaming.log 2>$null; git commit -m ''auto(bigbuy-gaming): PS5/Gaming-Import'' 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null' -WindowStyle Hidden }
      "tt-review-check" { & node "automation/local/tt-review-check.mjs"; git add -f automation/local/tt-review-shots/* reports/tt-review-check.json 2>$null; git commit -m "auto(tt-review-check): Ablehnungs-Grund der abgelehnten Ad ausgelesen" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "tt-events" { & node "automation/local/tt-events-check.mjs"; git add -f automation/local/tt-events-shots/* reports/tt-events-check.json 2>$null; git commit -m "auto(tt-events): TikTok Events Manager Screenshots (Pixel-Daten-Beweis)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "video-audit" { if(Test-Path "$env:USERPROFILE\luxe-secrets.ps1"){ . "$env:USERPROFILE\luxe-secrets.ps1" }; $env:MAX="60"; & node "automation/video-audit.mjs"; $env:MAX=$null; git add -f reports/video-audit.json 2>$null; git commit -m "auto(video-audit): Gemini-Vision QA aller Werbe-Videos" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "nanobanana" { Ensure-Campaign; & powershell -ExecutionPolicy Bypass -File "automation/local/nanobanana-batch.ps1"; git add -f social/ai-lifestyle/* 2>$null; git commit -m "auto(nanobanana): KI-Lifestyle-Bilder aus echten Produktbildern (Nano Banana 2)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "nanobanana-hero" { Ensure-Campaign; $env:NB_STYLE="hero"; $env:NB_MAX="6"; & powershell -ExecutionPolicy Bypass -File "automation/local/nanobanana-batch.ps1"; $env:NB_STYLE=$null; $env:NB_MAX=$null; git add -f social/ai-lifestyle/* 2>$null; git commit -m "auto(nanobanana-hero): dramatische Hero-Studio-Produktbilder (Nano Banana 2)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      "luma-hero" { Ensure-Campaign; & node "automation/luma_product_video.mjs" --pids 15402998792577 --ugc --no-attach --queue; git add -f reels/*.mp4 social/video_queue.csv 2>$null; git commit -m "auto(luma-hero): 1 Luma-Winner-Clip (cost-safe, Flame Diffuser)" 2>$null; git pull --rebase origin claude/luxestyle-product-CizQ6 2>$null; git push origin claude/luxestyle-product-CizQ6 2>$null }
      default        { Write-Host "  (unbekannt: $c)" }
    }
  }
} catch { } finally { Remove-Item $lock -ErrorAction SilentlyContinue }
