#!/usr/bin/env python3
"""Adds Swiss CHF price range sections to top Kaufberater pages.
Idempotent: marker data-aban-prices.
"""
import os, re, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER = "data-aban-prices"

PRICE_DATA = {
    "kaffeemaschine": ("Kaffeemaschine", "CHF 30–80", "Einfache Filterkaffeemaschine oder Kapselmaschine.", "CHF 80–300", "Kaffeevollautomat Einsteiger oder Siebträger-Einsteiger — gutes Preis-Leistungs-Verhältnis.", "ab CHF 300", "Vollautomaten mit Mahlwerk und Milchsystem; hochwertige Siebträger für Espresso-Enthusiasten."),
    "fernseher": ("Fernseher", "CHF 200–500", "32–43 Zoll HD/FHD, gute Bild­qualität für das Gästezimmer oder Schlafzimmer.", "CHF 500–1500", "55–65 Zoll 4K OLED/QLED, Smart TV mit guter Audio-Ausstattung — ideal für das Wohnzimmer.", "ab CHF 1500", "65–85 Zoll OLED/Mini-LED 4K, Premium-Bild­qualität, Dolby Atmos — für Heimkino-Fans."),
    "staubsauger": ("Staubsauger", "CHF 50–150", "Beutelstaubsauger oder einfacher Akkusauger — bewährt und zuverlässig.", "CHF 150–400", "Beutellos mit gutem Saugsystem oder Qualitäts-Akkusauger (Dyson-Klasse Einstieg).", "ab CHF 400", "Top-Akkusauger (Dyson V15 etc.) oder Premium-Bodenstaubsauger mit HEPA-Filter."),
    "laptop": ("Laptop", "CHF 400–700", "Allrounder für Büro, Web, Studium — meist Intel Core i5 / Ryzen 5, 8 GB RAM, SSD 256 GB.", "CHF 700–1400", "Schneller Allrounder bis Multimedia-Laptop: schnelle CPU, 16 GB RAM, FullHD oder WQHD-Display.", "ab CHF 1400", "Premium-Ultrabooks (MacBook Pro, Dell XPS), Workstations oder Gaming-Laptops mit dedizierter GPU."),
    "sofa": ("Sofa", "CHF 300–800", "Funktionale Sofas von Möbelhändlern — gut für Gäste- oder Kinderzimmer.", "CHF 800–2000", "Stoffsofa oder Leder, verschiedene Konfigurations­möglichkeiten, IKEA- bis Mittelklasse-Qualität.", "ab CHF 2000", "Designermöbel, echtes Leder, Schweizer Qualität — langlebige Investition fürs Wohnzimmer."),
    "saugroboter": ("Saugroboter", "CHF 100–250", "Einfacher Saugroboter ohne Mapping — saugt zuverlässig, navigiert zufällig.", "CHF 250–600", "Mit Lasernavigation/Mapping, App-Steuerung, Zeitprogramme — ideal für regelmässigen Einsatz.", "ab CHF 600", "Kombiroboter (Saugen+Wischen) mit Selbstreinigung, KI-Navigation und Hinderniserkennung."),
    "handy": ("Handy / Smartphone", "CHF 200–400", "Solide Mittelklasse — gute Kamera, ausreichend Leistung für Apps, Social Media, Navigation.", "CHF 400–800", "Gutes Display, schnelle Kamera, längere Updates — z. B. iPhone SE / Galaxy A-Serie.", "ab CHF 800", "Flagship-Smartphones: iPhone 15 Pro, Samsung Galaxy S25 etc. — beste Kamera, Top-Performance."),
    "tablet": ("Tablet", "CHF 150–300", "Android-Tablets für Streaming, E-Books und einfache Apps.", "CHF 300–700", "iPad (Standard) oder gute Android-Tablets mit flüssigem Display und langer Software-Unterstützung.", "ab CHF 700", "iPad Pro / Samsung Galaxy Tab S — für professionelle Nutzung, Stift, externe Tastatur."),
    "waschmaschine": ("Waschmaschine", "CHF 400–700", "8–9 kg Fassungsvermögen, 1200–1400 U/Min, Energieeffizienz A — solide Basisausstattung.", "CHF 700–1200", "10–11 kg, Inverter-Motor, Energieeffizienz A+, spezielle Waschprogramme.", "ab CHF 1200", "Miele/Siemens/Bosch Premium: langjährige Garantie, leiser Betrieb, maximale Effizienz."),
    "kuehlschrank": ("Kühlschrank", "CHF 300–600", "Standkühlschrank 200–300 L Nutzvolumen, NoFrost oder statisch, Energieeffizienz F–E.", "CHF 600–1200", "300–400 L, NoFrost, Edelstahl-Optik, Energieeffizienz E–D — ideal für Familien.", "ab CHF 1200", "Side-by-Side oder French Door ab 500 L, Energieeffizienz C+, Profi-Marken (Liebherr, Miele)."),
    "bohrmaschine": ("Bohrmaschine", "CHF 50–120", "Einfache Bohrmaschine für gelegentliche Heimwerkerprojekte — reicht für Dübel und Regalaufhängung.", "CHF 120–300", "Akkubohrschrauber (18V) mit gutem Drehmoment — für regelmässiges Heimwerken und Eigenheimarbeiten.", "ab CHF 300", "Profi-Akkubohrschrauber (z. B. Bosch Professional, Makita) — für intensive und handwerkliche Nutzung."),
    "espressomaschine": ("Espressomaschine", "CHF 80–250", "Siebträger-Einsteiger oder gute Kapselmaschine — für erste Schritte.", "CHF 250–800", "Halbautomaten mit gutem Druck, manueller Milchschäumer — für Kaffee-Enthusiasten.", "ab CHF 800", "Hochdruck-Siebträger mit Dampflanze, PID-Temperatursteuerung — für Barista-Qualität zu Hause."),
    # 8 neue Kaufberater-Seiten (2026-06-26)
    "fitness-tracker": ("Fitness-Tracker", "CHF 30–80", "Einfaches Aktivitäts-Band: Schrittzähler, Schlaf, Herzfrequenz — gut für Einsteiger.", "CHF 80–200", "GPS, SpO2, ausführliche Gesundheitsdaten — z. B. Garmin Vivofit, Fitbit Charge.", "ab CHF 200", "Vollwertige Smartwatch mit EKG, Sturzerkennung, langer Akkulaufzeit (Garmin/Apple Watch Ultra)."),
    "gaming-maus": ("Gaming-Maus", "CHF 30–60", "Kabelgebundene Maus mit gutem Sensor — ideal für Einsteiger und Gelegenheits-Gamer.", "CHF 60–120", "Hochpräziser optischer Sensor, anpassbare Gewichte, RGB — für regelmässige Gamer.", "ab CHF 120", "Drahtlose Premium-Mäuse (Logitech G Pro X, Razer) mit Top-Sensor und minimalem Input-Lag."),
    "solaranlage": ("Solaranlage / PV-Anlage", "CHF 800–2000", "Balkonkraftwerk 300–600 W (Plug-in) — einfach, keine Monteur­kosten, schnell amortisiert.", "CHF 4000–10000", "Kleinanlage 5–10 kWp mit Wechselrichter, inkl. CH-Förderung EVS/Einmalvergütung.", "ab CHF 15000", "Grosse Aufdach-Anlage 15–30 kWp + Batteriespeicher — maximale Eigenstrom­nutzung."),
    "powerstation": ("Powerstation / Portable Powerstation", "CHF 150–400", "200–500 Wh Kapazität — reicht für Camping, Handy, Laptop, kleine Geräte.", "CHF 400–1000", "500–1500 Wh, 1000 W AC-Ausgang — für Kühlboxen, CPAP, E-Bike-Laden.", "ab CHF 1000", "1500–3000 Wh, 2000 W+, LFP-Akkus (lange Lebensdauer) — fürs Homeoffice oder als Notstrom."),
    "balkonkraftwerk": ("Balkonkraftwerk / Steckersolar", "CHF 300–500", "1 Modul ~300–400 Wp, Balkon-Halterung, Plug-and-Play bis 600 W CH-Limit.", "CHF 500–900", "2 Module 600–800 Wp, hochwertiger Mikrowechselrichter (Hoymiles/Deye), App-Monitoring.", "ab CHF 900", "2–4 Module mit Batteriespeicher-Option, optimaler Wirkungsgrad, professionelle Montage."),
    "induktionskochfeld": ("Induktionskochfeld", "CHF 50–150", "1–2 Kochzonen, Tischgerät — ideal für die kleine Küche oder als Ergänzung.", "CHF 150–500", "4 Kochzonen Einbau, 7200 W, Boost-Funktion, Touch-Steuerung — gute Allround-Wahl.", "ab CHF 500", "Flex-Induktion, Bridge-Funktion, TFT-Display, Autarkie-Zonen — Siemens, Miele, Gaggenau."),
    "gasgrill": ("Gasgrill", "CHF 150–350", "2 Brenner, Gusseisen- oder Edelstahlrost, kompakt — für Balkon und kleinen Garten.", "CHF 350–800", "3–4 Brenner, Seitenkocher, Deckel-Thermometer, gute Grillleistung — Weber Spirit etc.", "ab CHF 800", "6+ Brenner, Infrarot-Heckbrenner, Sear-Station, Premium-Edelstahl — Weber Genesis/Summit, Napoleon."),
    "rollator": ("Rollator", "CHF 80–150", "Leichter Faltrollator, 4 Räder, Sitzmöglichkeit — bewährt für gelegentliche Nutzung.", "CHF 150–300", "Aluminium, leichter, ergonomische Griffe, gute Räder für drinnen+draussen.", "ab CHF 300", "Premium-Rollator (Carbon/Titan), sehr leicht, indoor/outdoor, KVG-anerkannt — ggf. Kassenpflicht."),
    # weitere populäre Kategorien
    "airfryer": ("Airfryer / Heissluftfritteuse", "CHF 40–100", "2–3 L Kapazität, Einzel-Korb — ideal für 1–2 Personen.", "CHF 100–200", "4–6 L, voreingestellte Programme, schnelle Aufheizzeit — gute Allround-Wahl.", "ab CHF 200", "Dual-Zone, 8+ L, Rotisserie, Smart-Anbindung — für Familien und Vielköche."),
    "akkuschrauber": ("Akkuschrauber / Akkubohrschrauber", "CHF 40–100", "10,8–12 V, Starter-Set mit 1–2 Akkus — für einfache Heimwerk­projekte.", "CHF 100–250", "18 V, gutes Drehmoment, Bürstenloser Motor — für regelmässiges Arbeiten.", "ab CHF 250", "18 V Profi (Bosch Professional, Makita, Festool) — für intensive Nutzung, langer Akku."),
    "beamer": ("Beamer / Projektor", "CHF 100–300", "HD-Beamer, 2500–3000 ANSI-Lumen — gut für verdunkeltes Heimkino.", "CHF 300–800", "Full-HD, 3000–5000 Lumen, kurze Aufheizzeit, gute Farb­darstellung.", "ab CHF 800", "4K-Beamer oder Kurzdistanz-Projektor mit hoher Helligkeit — für helle Räume und Business."),
    "bluetooth-lautsprecher": ("Bluetooth-Lautsprecher", "CHF 30–80", "Kompakt, IPX5, 10–20 h Akku — für unterwegs und Alltag.", "CHF 80–200", "360°-Sound, höherer Wirkungsgrad, wasserdicht IPX7 — z. B. JBL Charge, UE Boom.", "ab CHF 200", "Premium-Klang (Bose SoundLink Max, Sonos), Stereo-Pairing, Outdoor-tauglich."),
    "buerostuhl": ("Bürostuhl", "CHF 80–200", "Verstellbarer Drehstuhl für gelegentliche Nutzung — ausreichend für Homeoffice-Einsteiger.", "CHF 200–600", "Lendenstütze, Armlehnen 4D, Mesh-Rücken, ergonomisch zertifiziert.", "ab CHF 600", "Ergonomie-Stuhl (Herman Miller Aeron, Humanscale) — für tägliches 8h+ Arbeiten."),
    "computer": ("Desktop-Computer / PC", "CHF 400–700", "Intel Core i5 / Ryzen 5, 8–16 GB RAM, SSD 512 GB — gut für Büro und Web.", "CHF 700–1400", "Schnellerer Prozessor, dedizierte GPU, 32 GB RAM — für Multimedia, leichtes Gaming.", "ab CHF 1400", "Workstation oder Gaming-PC mit RTX 4080/4090 — für 3D, Videobearbeitung, High-End-Gaming."),
    "drucker": ("Drucker", "CHF 50–120", "Tintenstrahldrucker für Gelegenheits-Nutzer — günstig in der Anschaffung.", "CHF 120–350", "Multifunktions-Tintenstrahler oder Laser für häufiges Drucken — besseres Preis-Seite-Verhältnis.", "ab CHF 350", "Farblaser-Profi oder Fotodrucker (Canon, Epson) — für hohes Druckaufkommen oder Fotos."),
    "e-reader": ("E-Reader / E-Book-Reader", "CHF 80–120", "6 Zoll, Wi-Fi, gute Beleuchtung — reicht für alle E-Books und PDFs.", "CHF 120–200", "Wasserdicht, Warm-Beleuchtung, 8–32 GB — z. B. Kindle Paperwhite.", "ab CHF 200", "Kindle Oasis / Kobo Elipsa — grösseres Display, Stylus-Unterstützung, Premium-Haptik."),
    "ebike": ("E-Bike / Elektrovelo", "CHF 1500–2500", "Einsteiger-E-Bike, einfacher Motor, Reichweite 40–60 km — für gelegentliche Ausfahrten.", "CHF 2500–4500", "Mittelmotor (Bosch/Shimano), 80–120 km Reichweite, gute Komponenten.", "ab CHF 4500", "Premium-E-Bike (Trek, Haibike, Riese & Müller), langer Akku, hochwertige Schaltung."),
    "kopfhoerer": ("Kopfhörer", "CHF 30–80", "In-Ear oder Over-Ear ohne ANC — gut für Alltag und Sport.", "CHF 80–250", "ANC, Bluetooth 5.0, 20–30 h Akku — z. B. Sony WH-1000XM4, Bose QC45.", "ab CHF 250", "Premium-ANC (Sony, Bose, Apple AirPods Max) oder audiophile Studiokopfhörer."),
    "monitor": ("Monitor / PC-Bildschirm", "CHF 120–250", "24–27 Zoll FHD IPS, 75 Hz — solide Basis für Büro und Alltag.", "CHF 250–600", "27–32 Zoll QHD, 144 Hz, IPS/VA — für Gamer und kreative Arbeit.", "ab CHF 600", "4K OLED, 240 Hz, Ultra-Wide — für professionelle Grafik oder High-End-Gaming."),
    "spielkonsole": ("Spielkonsole", "CHF 350–450", "PlayStation 5 / Xbox Series S — aktuelle Generation, grosse Spieleauswahl.", "CHF 450–600", "PS5 Digital + Zubehör, Xbox Series X, Nintendo Switch OLED.", "ab CHF 600", "Konsole + Extra-Controller + Headset + Spiele — vollständiges Gaming-Paket."),
    "geschirrspueler": ("Geschirrspüler", "CHF 400–700", "60 cm Standgerät, 12–14 Gedecke, Energieeffizienz A — solide Basisausstattung.", "CHF 700–1200", "14+ Gedecke, 45 dB Lärm, Zeolithe-Trocknung, Kurz­programm.", "ab CHF 1200", "Vollintegriert, 42 dB, Premium-Marken (Miele, Siemens), Dampf-Funktion."),
    "rasenmaeher": ("Rasenmäher / Mähroboter", "CHF 200–500", "Bis 300 m², einfache Begrenzungs­draht-Navigation — gut für kleine Gärten.", "CHF 500–1200", "Bis 1000 m², Kameranavigation oder GPS, App-Steuerung.", "ab CHF 1200", "Grosse Flächen bis 3000+ m², KI-Navigation ohne Begrenzungsdraht, Gardena/Husqvarna."),
    "kinderwagen": ("Kinderwagen", "CHF 200–500", "Leichter Buggy oder einfaches Kombi-System — gut für den Alltag.", "CHF 500–1000", "Kombi-Kinderwagen mit Babywanne, geländetauglich, gute Federung.", "ab CHF 1000", "Premium (Stokke, Bugaboo, Cybex) — Design, Langlebigkeit, Schweizer Qualitäts­anspruch."),
    "wasserkocher": ("Wasserkocher", "CHF 20–50", "1,5–1,7 L, einfaches Design, 2200 W — kocht schnell und zuverlässig.", "CHF 50–120", "Temperaturwahl (60–100 °C), Keep-Warm-Funktion — ideal für Tee-Liebhaber.", "ab CHF 120", "Premium-Designwasserkocher (KitchenAid, Smeg, Fellow Stagg) — Optik + Präzisions­temperatur."),
    # Batch 3 — weitere populäre CH-Kategorien
    "3d-drucker": ("3D-Drucker", "CHF 200–400", "FDM-Einsteiger (Bambu Lab A1 Mini, Ender 3) — gut für erste Drucke.", "CHF 400–900", "Multi-Material, hohe Genauigkeit, grosse Baufläche — für Hobbyanwender und Maker.", "ab CHF 900", "Resin- oder Profi-FDM-Drucker — für hohe Auflösung, Ingenieursanwendungen."),
    "actioncam": ("Actionkamera", "CHF 100–250", "1080p / 4K-Einstieg, gute Stabilisierung — z. B. GoPro Hero12 Black Einstieg.", "CHF 250–450", "4K 60 fps, HyperSmooth, wasserdicht bis 10 m — GoPro Hero, Insta360 X4.", "ab CHF 450", "8K / 360°-Kamera, magnetische Halterungen, Cloud-Abo — für Profis und Sportler."),
    "autobatterie": ("Autobatterie", "CHF 60–100", "Standard-Blei-Säure (12V, 44–60 Ah) — passend für ältere Fahrzeuge.", "CHF 100–200", "AGM-Batterie (Start-Stopp) 70–100 Ah — für moderne Mittelklasse-Fahrzeuge.", "ab CHF 200", "EFB/AGM Premium (Bosch, Varta) oder Lithium-Starthilfe für grosse Motoren."),
    "babyphone": ("Babyphone", "CHF 30–80", "Einfaches Audio-Babyphone mit gutem Reichweiten­verhalten.", "CHF 80–200", "Videobabyphone mit Nachtsicht, Temperatursensor, App-Anbindung.", "ab CHF 200", "Full-HD-Kamera, Pan/Tilt, verschlüsselte Verbindung — z. B. Arlo, Nanit."),
    "bett": ("Bett / Bettrahmen", "CHF 200–500", "Holz- oder Metall-Bettrahmen, solide Qualität für das Schlafzimmer.", "CHF 500–1200", "Polsterbett, Lattenrost inklusive, gute Verarbeitung — IKEA bis Mittelklasse.", "ab CHF 1200", "Boxspringbett oder Schweizer Qualitätsbett (Hüsler Nest, Bico) — langlebige Investition."),
    "blutdruckmessgeraet": ("Blutdruckmessgerät", "CHF 20–50", "Handgelenk­messgerät, einfache Anzeige — ausreichend für gelegentliche Kontrolle.", "CHF 50–120", "Oberarm-Messgerät, klinisch validiert, Herzrhythmuserkennung — z. B. Omron M7.", "ab CHF 120", "Premium (Withings BPM Connect) mit App, EKG-Funktion, Langzeit­speicher."),
    "crosstrainer": ("Crosstrainer / Ellipsentrainer", "CHF 200–500", "Einsteigergerät, magnetisches Bremssystem, 8–12 kg Schwungmasse.", "CHF 500–1200", "Riemen-/Magnetbremse, 15–18 kg Schwungmasse, HF-Messung — für regelmässiges Training.", "ab CHF 1200", "Profi-Crosstrainer (NordicTrack, Life Fitness), app-gesteuert, Clubqualität."),
    "dampfreiniger": ("Dampfreiniger", "CHF 30–80", "Handgerät, 1000–1500 W — für Fugen, Badezimmer, kleine Flächen.", "CHF 80–200", "Bodendampfreiniger mit Zubehör-Set — Fliesen, Parkett, Küche.", "ab CHF 200", "Kärcher SC-Serie oder Profi mit Staubsaugerfunktion — für grosse Flächen."),
    "dashcam": ("Dashcam", "CHF 40–100", "Full-HD, Weitwinkel, Parküberwachung einfach — gut für den Einstieg.", "CHF 100–200", "2K/4K, GPS, ADAS-Fahrunterstützung, gute Nachtsicht.", "ab CHF 200", "Dual-Kamera (vorne+hinten), 4K, LTE-Cloudverbindung — für maximalen Schutz."),
    "drohne": ("Drohne / Quadrocopter", "CHF 100–300", "Kompakte Einsteiger-Drohne ohne Kamera oder HD — gut für erste Flüge.", "CHF 300–800", "DJI Mini 4 Pro o.ä.: 4K, GPS, automatische Rückkehr, App-Steuerung.", "ab CHF 800", "DJI Air 3 / Mavic 3 — 4K Dual-Kamera, langer Akku, Profi-Features."),
    "e-scooter": ("E-Scooter / Elektro-Roller", "CHF 300–600", "25 km/h, Reichweite 20–30 km, Klingelvorschrift CH erfüllt.", "CHF 600–1000", "Bessere Federung, Pneumatik-Reifen, 35–50 km Reichweite, App.", "ab CHF 1000", "Segway-Ninebot Max oder Ultra-Reichweite mit Bremslicht + Blinker — CH-legal."),
    "gefriertruhe": ("Gefriertruhe / Tiefkühler", "CHF 150–300", "80–150 L, Energieeffizienz F/G — gut für saisonale Vorräte.", "CHF 300–600", "200–300 L, NoFrost oder manuell, Energieeffizienz E/D — ideal für Familien.", "ab CHF 600", "350+ L oder Gefrierschrank Premium (Liebherr) — für grosse Vorratshaltung."),
    "gaming-headset": ("Headset / Headphones Gaming", "CHF 30–70", "Kabelgebundenes Stereo-Headset, gute Sprachqualität für Calls und Gaming.", "CHF 70–200", "Virtual-7.1-Surround, diskrete Mikrofon­kapsel, wireless — z. B. SteelSeries, HyperX.", "ab CHF 200", "Profi-Headset mit Boom-Mikrofon (Rode, Shure), Noise-Gate — für Streaming und Broadcasting."),
    "hometrainer": ("Heimtrainer / Fahrradergometer", "CHF 150–350", "Magnetbremse, einfache LCD-Anzeige, solide Grundausstattung.", "CHF 350–800", "App-kompatibel (Zwift/Wahoo), stärkere Schwungmasse, leiser Riemenantrieb.", "ab CHF 800", "Smart-Bike (Tacx Neo, Wahoo Kickr) — für ernsthaftes Indoortraining."),
    "kaffeevollautomat": ("Kaffeevollautomat", "CHF 200–500", "Einsteiger-Vollautomat mit einfachem Mahlwerk und Espresso/Café-Crème.", "CHF 500–1200", "Integriertes Milchsystem, Keramikmahlwerk, 15 bar — z. B. Jura E8, DeLonghi Magnifica.", "ab CHF 1200", "Jura Z10, Siemens EQ.900 — One-Touch-Latte, KI-Mahlgrad, Profi-Qualität zu Hause."),
    "klimaanlage-mobil": ("Mobile Klimaanlage", "CHF 200–400", "Monoblock 9000–12000 BTU — für gelegentliche Nutzung im Sommer.", "CHF 400–700", "Dual-Hose 12000–14000 BTU, effizienter, leiser Betrieb.", "ab CHF 700", "Decken-Split (fest) oder leistungsstarkes Monoblock mit Wärmepumpe."),
    "luftreiniger": ("Luftreiniger / Luftfilter", "CHF 50–120", "Kompakter HEPA-Filter, 20–40 m² — gut für Schlafzimmer und Büro.", "CHF 120–300", "HEPA H13 + Aktivkohle, Partikelzähler, Autobetrieb — z. B. Xiaomi, Philips.", "ab CHF 300", "Coway, Blueair — extra leise, CADR 400+, für Allergiker und grosse Räume."),
    "mikrowelle": ("Mikrowelle / Mikrowellenofen", "CHF 50–120", "Solo-Mikrowelle 17–23 L, 700–900 W — gut für Aufwärmen und einfaches Garen.", "CHF 120–300", "Kombi-Mikrowelle mit Grill und Heissluft — vielseitiger Einsatz.", "ab CHF 300", "Einbau-Mikrowelle oder Steam-Ofen (Miele, Gaggenau) — für die Einbauküche."),
    "nass-trockensauger": ("Nass-Trocken-Sauger", "CHF 50–120", "20–30 L, 1000–1200 W — gut für Keller, Garage, Baustelle.", "CHF 120–250", "Automatische Filterwechslung, Blasfunktion, robuste Bauweise.", "ab CHF 250", "Kärcher WD-Profi-Serie — für intensiven Einsatz auf der Baustelle."),
    "waeschetrockner": ("Wäschetrockner", "CHF 400–700", "Ablufttrockner oder einfacher Kondensationstrockner, 7–8 kg.", "CHF 700–1200", "Wärmepumpentrockner 8–9 kg, Energieeffizienz A+++ — deutlich günstiger im Betrieb.", "ab CHF 1200", "Wärmepumpe Premium (Miele, Siemens) mit Vollautomatik und Dampf-Auffrischung."),
    "zahnbuerste-elektrisch": ("Elektrische Zahnbürste", "CHF 20–50", "Einfache Rotations- oder Sonic-Zahnbürste — deutlich besser als manuell.", "CHF 50–150", "Oral-B iO / Philips Sonicare mit Bluetooth, Drucksensor, Putz-Timer.", "ab CHF 150", "Oral-B iO Series 9 / Philips DiamondClean — KI-Erkennung, Premium-Material."),
    "solar-gartenleuchten": ("Stehlampe / Gartenleuchte", "CHF 30–80", "Einfache Stehlampe, E27-Fassung — passt in jedes Wohnzimmer.", "CHF 80–200", "Dimm­bar, integrierte LED, gute Materialgüte — z. B. IKEA RANARP bis Mittelklasse.", "ab CHF 200", "Designerleuchte (Artemide, Flos) oder Smart-Stehlampe mit Licht­temperatur."),
    "ueberwachungskamera": ("Überwachungskamera", "CHF 30–80", "Innen-IP-Kamera, Full-HD, App — gut für Heimüberwachung.", "CHF 80–200", "Aussen-Kamera, 4K, Bewegungserkennung, lokaler Speicher, DSGVO-konform.", "ab CHF 200", "Arlo Ultra 2, Eufy Cam 3 — 4K, KI-Personenerkennung, kabellos mit Solar."),
    "gaming": ("Gaming-Zubehör / PC-Gaming", "CHF 50–150", "Maus + Tastatur + Headset Einstieg-Set — gut für Freizeit-Gamer.", "CHF 150–400", "Mechanische Tastatur, präzise Gaming-Maus, 7.1-Headset — für regelmässiges Spielen.", "ab CHF 400", "Profi-Peripherie (Razer, SteelSeries, Corsair) — für kompetitives Gaming."),
    "gamingstuhl": ("Gaming-Stuhl / Racing-Chair", "CHF 80–200", "Bucket-Seat-Stil, verstellbare Armlehnen — für gelegentliches Gaming.", "CHF 200–450", "Lendenwirbelstütze, Leder/Mesh, gut verarbeitet — z. B. Secretlab Titan.", "ab CHF 450", "Herman Miller x Logitech, Ergonomie + Gaming-Design vereint — Top-Komfort."),
    # Batch 4
    "kuechenmaschine": ("Küchenmaschine / Foodprozessor", "CHF 60–150", "Kompakter Handmixer oder einfache Küchenmaschine — gut für Teig und Saucen.", "CHF 150–500", "Küchenmaschine mit Schüssel (KitchenAid Artisan Einstieg, Bosch MUM) — fürs regelmässige Backen.", "ab CHF 500", "KitchenAid Artisan Premium, Thermomix, Kenwood Chef — für begeisterte Köche."),
    "laufband": ("Laufband / Heimtraining", "CHF 300–600", "Einsteiger-Laufband, max. 12 km/h, 100 kg Traglast — für Gehen und leichtes Joggen.", "CHF 600–1500", "Bis 18 km/h, app-kompatibel (Zwift, Kinomap), gut gedämpft.", "ab CHF 1500", "NordicTrack, Life Fitness — motorisiert leise, grosse Lauf­fläche, Profi-Dämpfung."),
    "naehmaschine": ("Nähmaschine", "CHF 80–200", "Einstiegsgerät mit Grundstichen, gut für Reparaturen und Anfänger.", "CHF 200–500", "Computergesteuert, 100+ Stiche, Stickfunktion — z. B. Singer, Brother.", "ab CHF 500", "Overlock- oder Stickmaschine, Profi-Qualität (Bernina, Pfaff) — für Schneiderinnen."),
    "powerbank": ("Powerbank / Mobile Ladestation", "CHF 20–50", "5000–10000 mAh, USB-A, kompakt — reicht für 1–2 Handy-Ladungen.", "CHF 50–120", "20000 mAh, USB-C PD 45 W, schnellladen für mehrere Geräte.", "ab CHF 120", "27000 mAh, 100 W PD, Laptop-tauglich — Anker, Zendure oder GaN-Lösung."),
    "sandwichmaker": ("Sandwichmaker / Waffel­eisen", "CHF 20–50", "Einfacher Sandwichmaker, 700–900 W — günstig und zuverlässig.", "CHF 50–120", "Wechselbare Platten (Grill, Waffle, Panini), schnelle Aufheiz­zeit.", "ab CHF 120", "Multifunktions-Kontaktgrill (Tefal OptiGrill) mit Automatik­programmen."),
    "smart-home-gadgets": ("Smart-Home-Geräte", "CHF 20–60", "Smarte Steckdose, Glühbirne (Philips Hue Starter) — einfacher Einstieg.", "CHF 60–200", "Hub oder Bridge, mehrere Geräte, Sprachsteuerung (Alexa/Google), App-Automatisierung.", "ab CHF 200", "Matter-kompatibles Ökosystem (Apple Home, Google Home) — umfassende Steuerung."),
    "smartwatch": ("Smartwatch", "CHF 100–250", "Grundlegende Fitness-Funktionen, Benachrichtigungen, 5–7 Tage Akku.", "CHF 250–500", "EKG, SpO2, GPS, Sturzerkennung — z. B. Apple Watch SE, Samsung Galaxy Watch.", "ab CHF 500", "Apple Watch Ultra, Garmin Fenix — Profi-Outdoor-Funktionen, Titan-Gehäuse."),
    "standmixer": ("Standmixer / Hochleistungsmixer", "CHF 30–80", "Basisgerät, 500–700 W — für Smoothies, Suppen und einfache Mixes.", "CHF 80–200", "800–1200 W, Eis-Crushing, Glaskaraffe — z. B. WMF Kult, Philips.", "ab CHF 200", "Vitamix, Blendtec — 2 PS+ Motor, 10 Jahre Garantie, für täglichen Einsatz."),
    "yogamatte": ("Yogamatte", "CHF 15–40", "PVC oder TPE, 6 mm — günstig und strapazierfähig für Einsteiger.", "CHF 40–80", "Naturgummi oder Kork, rutschfest, umweltfreundlich — z. B. Manduka PRO Lite.", "ab CHF 80", "Manduka PRO, Liforme — Premium-Haftung, 6 mm, lebenslange Garantie."),
    "handstaubsauger": ("Handstaubsauger / Akku-Handstauber", "CHF 20–60", "Kompakter Handstauber, 5–10 Min Laufzeit — für Sofa, Auto, kleine Flächen.", "CHF 60–150", "Dyson V8 Slim etc., 20+ Min, gute Saugleistung, Zubehör inklusive.", "ab CHF 150", "Dyson Micro — extrem leicht, hohe Saugleistung, HEPA, ideal für Allergiker."),
    "kuehlbox": ("Kühlbox / Camping-Kühlschrank", "CHF 30–80", "Passiv-Kühlbox (Styropor/Hartschale) — für Tages­ausflüge und Picknick.", "CHF 80–250", "Elektrische 12-V-Kühlbox, 20–40 L — für Camping und lange Autofahrten.", "ab CHF 250", "Kompressor-Kühlschrank (BioLite, Dometic) — echte Kühlung bis –20 °C, geräuschlos."),
    # Batch 5
    "aroma-diffuser": ("Aroma-Diffuser / Luftbefeuchter", "CHF 20–50", "Ultraschall-Diffuser, 100–300 ml, Timer — gut für Schlafzimmer und kleines Büro.", "CHF 50–120", "400–500 ml, mehrere Licht-Modi, stiller Betrieb, Zeitprogramme.", "ab CHF 120", "Design-Diffuser (Stadler Form, Beurer) — grosses Volumen, HEPA, Sensor."),
    "babybett": ("Babybett / Kinderbett", "CHF 80–200", "Standard-Babybett 60×120 cm, stabile Latten — solide Basis für Neugeborene.", "CHF 200–450", "Verstellbarer Boden, umbaubar zu Juniorbett, gute Verarbeitung.", "ab CHF 450", "Premium-Design (Stokke Sleepi, Leander) — langlebig, umbaubar bis Schulalter."),
    "bartschneider": ("Bartschneider / Haarschneider", "CHF 20–50", "Kabelgebunden, 3–5 Längen-Aufsätze — für regelmässiges Trimmen.", "CHF 50–120", "Akkubetrieb, Titan-Klingen, genaues Trimmen bis 0,2 mm — z. B. Philips, Braun.", "ab CHF 120", "Profi-Barber-Set (Wahl, Andis), Laserführung, Barber-Aufsätze."),
    "buegeleisen": ("Bügeleisen / Dampfbügeleisen", "CHF 20–50", "Leichtes Dampfbügeleisen, Edelstahl-Sohle, 2000 W — gut für den Alltag.", "CHF 50–120", "Dampfstoss, Auto-Abschaltsicherheit, Titanium-Sohle — z. B. Philips Azur.", "ab CHF 120", "Profi-Dampfbügeleisen mit separatem Boiler (Braun CareStyle, Tefal) — für Profis."),
    "dampfgarer": ("Dampfgarer / Steamer", "CHF 40–100", "Einfacher Dampfgarer, 2–3 Etagen, Timer — gesundes Garen ohne Fett.", "CHF 100–250", "Digitaler Dampfgarer, Warmhalte­funktion, integrierter Reisbehälter.", "ab CHF 250", "Combi-Dampfgarer (Miele, Gaggenau) für Einbau — vitaminschonendes Garen."),
    "elektrogrill": ("Elektrogrill / Kontaktgrill", "CHF 30–80", "Tisch-Elektrogrill, 1500–2000 W — schnell einsatzbereit, ohne Rauch.", "CHF 80–200", "Wechselbare Platten, Fettauffang, Temperaturregler — z. B. Tefal OptiGrill.", "ab CHF 200", "Gusseisen-Elektrogrill mit Haube, Weber-Feeling ohne Gas."),
    "friteuse": ("Fritteuse / Heissluftfritteuse", "CHF 30–80", "Klassische Fritteuse 1–2 L oder einfacher Airfryer — für gelegentliches Frittieren.", "CHF 80–200", "2,5–4 L Airfryer mit voreingestellten Programmen, schnelle Aufheizzeit.", "ab CHF 200", "Dual-Zone Airfryer (8 L+) oder Edelstahl-Öl-Fritteuse für häufige Nutzung."),
    "grill": ("Grill / Holzkohlegrill", "CHF 30–100", "Einweggrills oder einfacher Kugelgrill — für saisonale Nutzung.", "CHF 100–350", "Weber Kugelgrill (57 cm), robuste Verarbeitung, Deckel — der Klassiker.", "ab CHF 350", "Weber Kettle Premium oder Keramik-Grill (Big Green Egg) — für Grill-Enthusiasten."),
    "haartrockner": ("Haartrockner / Föhn", "CHF 20–50", "1800–2000 W, 2 Temperaturstufen — zuverlässig für den Alltag.", "CHF 50–150", "Ionentechnologie, Diffusor, schnelle Trocknung — z. B. Dyson Supersonic Einstieg.", "ab CHF 150", "Dyson Supersonic / Airwrap — schonende Trocknung, Styling-Aufsätze."),
    "fieberthermometer": ("Fieberthermometer", "CHF 10–25", "Digital-Thermometer oral/axillar, schnelle Messung — gut für den Alltag.", "CHF 25–70", "Stirn- oder Ohrthermometer, kontaktlos, 1-Sek.-Messung.", "ab CHF 70", "Medizin-Präzisions-Thermometer (Braun ThermoScan 7) — für Kleinkinder."),
    "gartenpumpe": ("Gartenpumpe / Bewässerungspumpe", "CHF 50–120", "Tauch- oder Kreiselpumpe 600–1000 W — gut für Teich und Regentonne.", "CHF 120–300", "Automatik-Hauswasserwerk, Druckbehälter, Sandfilter-tauglich.", "ab CHF 300", "Profi-Pumpe für Brunnen, Tiefbrunnenpumpe (Grundfos, Gardena)."),
    "gaskocher": ("Gaskocher / Campingkocher", "CHF 20–50", "Einfacher Einzel-Gaskocher, Kartuschensystem — leicht und kompakt.", "CHF 50–120", "Doppelkocher oder Premium-Einzel (MSR, Primus) — für Alpine-Touren.", "ab CHF 120", "Benzin-Multifuel-Kocher — extrem kalt und hoch zuverlässig."),
    "heckenschere": ("Heckenschere / Strauchschere", "CHF 30–80", "Akku-Heckenschere 18 V, 45–50 cm Klingenbar — gut für kleine Hecken.", "CHF 80–200", "60 cm+ Klingenbar, Anti-Blockier-Automatik, Doppelklinge — z. B. Gardena, Bosch.", "ab CHF 200", "Profi-Akku (Stihl, Husqvarna) — für häufige Nutzung und grosse Flächen."),
    "heizkoerperthermostat": ("Heizkörper-Thermostat / Smart Thermostat", "CHF 15–40", "Mechanisches oder einfaches elektronisches Thermostat — Basis-Steuerung.", "CHF 40–80", "Smart-Thermostat (Tado, Netatmo) mit App, Geofencing, Energiesparen.", "ab CHF 80", "Komplettes Smart-Heating-System mit Zentrale, alle Heizkörper vernetzt."),
    "eierkocher": ("Eierkocher", "CHF 15–30", "Einfacher Eierkocher, 6–7 Eier — schnell und günstig.", "CHF 30–60", "7 Eier, Omelette-Schale, Härteregler, Abschaltsicherheit.", "ab CHF 60", "Multifunktions-Dampfgarer inkl. Eierkocher-Funktion."),
    "epilierer": ("Epilierer / Haarentferner", "CHF 30–70", "Einfacher Epilierer, Schnurgebunden, 20–24 Zangen — für Bein­enthaarung.", "CHF 70–150", "Kabellos, nass/trocken, Massage-Rollenaufsatz — z. B. Braun Silk-épil.", "ab CHF 150", "Braun Silk-épil 9 Flex — 40 Zangen, Smartlight, vollständig schmerzärmer."),
    "fenstersauger": ("Fenstersauger / Fensterreiniger", "CHF 30–60", "Einfacher Fenstersauger, 25–30 cm Absaugbreite — gut für kleinere Fenster.", "CHF 60–120", "Kärcher WV 2 Plus — Akku, Sprühaufsatz, streifenfreies Ergebnis.", "ab CHF 120", "Kärcher WV 6 mit WLAN, grössere Saugleiste — für Fassaden und grosse Fensterfronten."),
    "fernglas": ("Fernglas / Binokulare", "CHF 30–80", "8×42 oder 10×42, beschichtete Linsen — gut für Wandern und Konzerte.", "CHF 80–250", "Porro- oder Dachkant-Optik, wasserdicht, Phasenbeschichtung — z. B. Nikon Prostaff.", "ab CHF 250", "Zeiss Victory, Swarovski — brillantste Optik für Vogelbeobachtung und Jagd."),
    "buegelstation": ("Bügelstation / Dampfbügelstation", "CHF 80–150", "Einstiegs-Dampfstation, 3,5–4 Bar Dampfdruck — besser als normales Bügeleisen.", "CHF 150–300", "5–6 Bar, grosser Tank, Selbstreinigungs­programm — z. B. Philips PerfectCare.", "ab CHF 300", "Profi-Dampfbügelstation (Laurastar, Polti) — 6–8 Bar, für grosse Bügelmengen."),
    # Batch 6
    "handy-zubehoer": ("Handy-Zubehör / Smartphone-Accessoires", "CHF 10–30", "Schutzhülle, Displayschutzfolie, Ladekabel — Basis-Ausstattung für jedes Smartphone.", "CHF 30–80", "MagSafe-Zubehör, kabellose Ladesysteme, Gimbal-Stabilisator.", "ab CHF 80", "Profi-Kamera-Objektiv-Clip, Laowa-Macro, Mobile Studio — für Smartphone-Fotografie."),
    "hantelbank": ("Hantelbank / Trainingsbank", "CHF 50–120", "Flache Bank, bis 150 kg Belastung — gut für Einsteiger-Krafttraining.", "CHF 120–300", "Verstellbare Neigung, Klappbar, 300 kg+ — z. B. Marcy, Body-Solid.", "ab CHF 300", "Profi-Verstellbank (ATX, Taurus) — stabil, Vario-Neigung, für intensives Training."),
    "haustierbedarf": ("Haustierbedarf / Heimtierbedarf", "CHF 20–50", "Futterschüssel, Transportbox, Spielzeug — das Wichtigste für Hund oder Katze.", "CHF 50–150", "Automatischer Futterautomat, Katzenbaum, Hundetraining.", "ab CHF 150", "GPS-Tracker, Smart-Feeder, orthopädisches Tierbett — Premium-Ausstattung."),
    "kaminofen": ("Kaminofen / Holzofen", "CHF 500–1200", "Einstiegs-Kaminofen 5–6 kW, guter Wirkungsgrad — CH-Norm TA Luft konform.", "CHF 1200–2500", "7–9 kW, Speicher­masse, Seiten­scheiben, Wärme­abgabe Anpassbar.", "ab CHF 2500", "Design-Kaminofen (Attika, Brunner, Austroflamm) — Schweizer Qualität, Speichermasse."),
    "kinderfahrrad": ("Kinderfahrrad", "CHF 100–200", "Laufrad oder einfaches 12-Zoll-Fahrrad — gut für Kleinkinder 2–4 Jahre.", "CHF 200–400", "16–20 Zoll, Schutzbleche, Stützräder, gute Bereifung — 5–8 Jahre.", "ab CHF 400", "Qualitäts-Kinderrad (Puky, Ghost, Scott) — leicht, sicherere Bremsen, wächst mit."),
    "kinderroller": ("Kinderroller / Tretroller", "CHF 30–70", "Einfacher Tretroller, 3 Räder, Standfläche — für Kinder ab 2 Jahren.", "CHF 70–150", "Stufenlose Höhenverstellung, Lightweight-Rahmen — z. B. Micro Mini Deluxe.", "ab CHF 150", "Micro Maxi Deluxe, LED-Räder, ergonomischer Lenker — Premium für Kinder 5–12 J."),
    "lautsprecher": ("Lautsprecher / HiFi-Lautsprecher", "CHF 80–200", "Kompakte Regalbox oder guter Bluetooth-Lautsprecher für Zimmer-HiFi.", "CHF 200–600", "Stereo-Paar 2.0, guter Wirkungsgrad, Bassreflex — z. B. Klipsch, KEF.", "ab CHF 600", "Standlautsprecher, passive Profi-Box (Focal, B&W) — für echtes HiFi-Erlebnis."),
    "luftbefeuchter": ("Luftbefeuchter / Verdunster", "CHF 20–50", "Ultraschall-Befeuchter, 2 L Tank, einfache Steuerung — gut für ein Zimmer.", "CHF 50–150", "Verdunstungs-Befeuchter (hygienischer), Hygrostat, grösserer Tank.", "ab CHF 150", "Stadler Form Karl Big, Dyson Purifier Humidify — HEPA, UV-C-Keim­töter."),
    "luftentfeuchter": ("Luftentfeuchter / Raumtrockner", "CHF 30–80", "Desiccant-Mini-Gerät, 10 m² — gut gegen Feuchtigkeit im Keller.", "CHF 80–250", "Kompressor-Entfeuchter 20–30 L/Tag, automatisch — z. B. Comfee, Trotec.", "ab CHF 250", "Profi-Entfeuchter 50 L/Tag (Trotec, DeLonghi) — für Keller und Baustelle."),
    "mikrofon": ("Mikrofon / Podcast-Mikrofon", "CHF 30–80", "USB-Kondensatormikrofon — gut für Home-Office-Calls und erste Podcast-Aufnahmen.", "CHF 80–200", "Shure MV7, Blue Yeti — XLR oder USB, dynamisch oder Kondensator.", "ab CHF 200", "Shure SM7B, Rode NT1 — Profi-Broadcast-Qualität für Podcast und Studio."),
    "rasentraktor-xxx": ("Aufsitzrasenmäher / Rasentraktor", "CHF 800–2000", "Seitenauswurf, 80–90 cm Schnittbreite — gut für mittelgrosse Gärten.", "CHF 2000–4000", "Fangkorb, 100–120 cm, Hydrostat-Getriebe — für 2000–5000 m².", "ab CHF 4000", "Zero-Turn-Mäher oder Husqvarna Rider — für grosse Flächen ab 5000 m²."),
    "wischroboter": ("Saugroboter / Wischroboter", "CHF 100–250", "Einfacher Saugroboter ohne Mapping — zuverlässig, navigiert zufällig.", "CHF 250–600", "Lasernavigation, App, Zeitprogramme, gute Saugleistung.", "ab CHF 600", "Saugen + Wischen + Selbstreinigung, KI-Hinderniserkennung."),
    "velohelm": ("Fahrradhelm / Velohelm", "CHF 30–80", "CE-zertifizierter Einsteiger­helm, gute Ventilation — Pflicht bei E-Bikes.", "CHF 80–200", "MIPS-Schutz­system, aerodynamisch, leicht — z. B. Giro, Specialized.", "ab CHF 200", "Carbon-Helm, Aero-Design, MIPS — für Road oder MTB-Profis."),
    "schreibtisch": ("Schreibtisch / Höhenverstellbarer Schreibtisch", "CHF 150–350", "Manuell höhenverstellbarer Schreibtisch — günstig, für gelegentliches Stehen.", "CHF 350–700", "Elektrisch, Motorantrieb, Speicher­positionen — z. B. Flexispot, Uplift.", "ab CHF 700", "Profi-Stehschreibtisch (Vari, Herman Miller) — stabiler Motor, breite Fläche."),
    "werkzeug": ("Werkzeugkoffer / Werkzeugset", "CHF 30–80", "Basic-Werkzeugkoffer mit Hammer, Schrauben­dreher, Zange — gut für den Haushalt.", "CHF 80–200", "Komplettes Set mit Bit-Box, Wasserwaage, Zollstock — für Heimwerker.", "ab CHF 200", "Profi-Koffer (Wera, Knipex, Stanley FatMax) — für ernsthafte Handwerks­arbeit."),
    "trampolin": ("Trampolin / Gartentrampolin", "CHF 100–250", "244 cm Durchmesser, Sicherheitsnetz — gut für Kinder bis 10 Jahre.", "CHF 250–500", "305–366 cm, TÜV-geprüft, verstärkte Federn — für Familien.", "ab CHF 500", "Acon, Jumpking Premium — Inground oder Profi-Outdoor, 10+ Jahre Lebensdauer."),
    "trockenhaube-xxx": ("Haartrockner-Haube / Trockenhaube", "CHF 30–60", "Einfache Trockenhaube, 500–900 W — gut für Locken und Farbe.", "CHF 60–150", "Professionelle Salon-Haube, Zeitschalter, gleichmässige Wärme.", "ab CHF 150", "Profi-Standfön (Wella, Goldwell) — für Friseur-Qualität zu Hause."),
    "wanderrucksack": ("Wanderrucksack / Trekkingrucksack", "CHF 50–120", "20–30 L, leichter Rahmen — gut für Tagestouren in der Schweiz.", "CHF 120–250", "35–50 L, Hüftgurt, Regenschutz — für mehrtägige Alpin-Touren.", "ab CHF 250", "Osprey, Gregory, Deuter 60+ L — Profi-Fit, lang­lebige Materialien, Rückenbelüftung."),
    "wanderschuhe": ("Wanderschuhe / Trekkingschuhe", "CHF 60–120", "Leichter Wanderschuh, Gore-Tex — gut für Spaziergänge und Tagestouren.", "CHF 120–200", "Halbhohe Knöchelstütze, Vibram-Sohle, Gore-Tex — z. B. Salomon X Ultra, Meindl.", "ab CHF 200", "Hochalpine Bergschuhe (Hanwag, Lowa) — steigeisen­tauglich, für Gletscher und Klettersteige."),
    "sodastream": ("Wassersprudler / SodaStream", "CHF 50–100", "SodaStream Art oder Terra — einfache Bedienung, bis 60 L pro Zylinder.", "CHF 100–180", "SodaStream Duo mit Glasflaschen-Option, elegantes Design.", "ab CHF 180", "SodaStream Sparkling Water Creator oder Brita SodaONE — Premium-Optik und mehr Kontrolle."),
    "wildkamera-xxx": ("Wildkamera / Fotofalle", "CHF 40–100", "Einstiegs-Wildkamera, 12 MP, Nachtsicht, PIR-Sensor — gut für Garten und Feld.", "CHF 100–200", "4K-Video, schneller PIR, lange Akkulaufzeit, App-Verbindung.", "ab CHF 200", "Spypoint LINK-MICRO LTE — Mobilfunk, Direktversand von Fotos aufs Handy."),
}

SECTION_TMPL = """
<div class="price-ranges" data-aban-prices style="margin:22px 0 8px">
  <h2 style="font-size:1.3rem;margin-bottom:10px">Preisklassen in der Schweiz</h2>
  <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(195px,1fr));gap:10px">
    <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-left:4px solid #059669;border-radius:10px;padding:13px 14px">
      <strong style="color:#059669">💚 Budget · {b_range}</strong>
      <p style="font-size:.88rem;color:#374151;margin-top:4px">{b_text}</p>
    </div>
    <div style="background:#fff7ed;border:1px solid #fed7aa;border-left:4px solid #d97706;border-radius:10px;padding:13px 14px">
      <strong style="color:#d97706">🔶 Mittelklasse · {m_range}</strong>
      <p style="font-size:.88rem;color:#374151;margin-top:4px">{m_text}</p>
    </div>
    <div style="background:#faf5ff;border:1px solid #e9d5ff;border-left:4px solid #7c3aed;border-radius:10px;padding:13px 14px">
      <strong style="color:#7c3aed">⭐ Premium · {p_range}</strong>
      <p style="font-size:.88rem;color:#374151;margin-top:4px">{p_text}</p>
    </div>
  </div>
</div>
"""


def process(path, key):
    with open(path, encoding="utf-8") as f:
        html = f.read()
    if MARKER in html:
        return False, "skip"

    data = PRICE_DATA[key]
    _, b_range, b_text, m_range, m_text, p_range, p_text = data
    section = SECTION_TMPL.format(
        b_range=b_range, b_text=b_text,
        m_range=m_range, m_text=m_text,
        p_range=p_range, p_text=p_text,
    )

    # Insert before the FAQ h2
    target = re.search(r'<h2[^>]*>H.ufige Fragen</h2>', html)
    if not target:
        # fallback: before cta2
        target = re.search(r'<div class="cta2">', html)
    if not target:
        return False, "no-target"

    new_html = html[:target.start()] + section + html[target.start():]
    with open(path, "w", encoding="utf-8") as f:
        f.write(new_html)
    return True, key


def main():
    done = skipped = errors = 0
    for key, data in PRICE_DATA.items():
        pattern = os.path.join(ROOT, f"{key}-kaufen-schweiz.html")
        matches = glob.glob(pattern)
        if not matches:
            print(f"  · {key}: not found")
            errors += 1
            continue
        for path in matches:
            ok, info = process(path, key)
            fname = os.path.basename(path)
            if ok:
                done += 1
                print(f"  ✓ {fname}")
            elif info == "skip":
                skipped += 1
            else:
                errors += 1
                print(f"  · {fname}: {info}")
    print(f"\n✅ {done} bearbeitet · {skipped} skip · {errors} Fehler")


# Batch 7 — weitere populäre CH-Kategorien
_BATCH7 = {
    "hochdruckreiniger": ("Hochdruckreiniger", "CHF 50–120", "120–150 bar, 1500–1800 W — gut für Terrasse, Auto, Gartenmöbel.", "CHF 120–250", "160–200 bar, Kärcher K5–K6 — für härtere Reinigungsaufgaben.", "ab CHF 250", "Kärcher K7 Professional — 180 bar, langer Schlauch, für intensive Nutzung."),
    "klimageraet": ("Klimagerät / Split-Klimaanlage", "CHF 500–1000", "Monosplit 2,5 kW (A++), 25–30 m² — guter Einstieg, Kühlen + Heizen.", "CHF 1000–2000", "Multi-Split oder leistungsstärker 3,5 kW — für grössere Räume.", "ab CHF 2000", "Inverter A+++ Multi-Split (Mitsubishi, Daikin) — sehr leise, maximale Effizienz."),
    "kamera": ("Digitalkamera / Systemkamera", "CHF 300–600", "Einsteiger-Spiegellose oder Bridge-Kamera — gut für Reise und Familie.", "CHF 600–1500", "APS-C Systemkamera (Sony ZV-E10, Fujifilm X-S20) — ausgezeichnete Bildqualität.", "ab CHF 1500", "Vollformat (Sony A7, Nikon Z6) — professionelle Fotografie, tolle Lichtempfindlichkeit."),
    "soundbar": ("Soundbar / Heimkino-Soundbar", "CHF 80–200", "2.0 Soundbar, guter TV-Klang-Aufwertung — kompakt und einfach.", "CHF 200–600", "2.1 mit Subwoofer, Dolby Atmos, HDMI eARC — z. B. Samsung Q600C, Sonos Ray.", "ab CHF 600", "3.1.2 oder 5.1.2 Dolby Atmos, Surround-Sound (Sonos Arc, JBL Bar 1000)."),
    "toaster": ("Toaster / Brötchen-Röster", "CHF 20–40", "2-Scheiben-Toaster, 700–900 W — zuverlässig für den Alltag.", "CHF 40–80", "4-Scheiben, Aufwärm-Funktion, Brochen-Aufsatz — z. B. Severin, WMF.", "ab CHF 80", "Designtoaster (Dualit, Smeg) — Premium-Optik, lange Lebensdauer."),
    "pfannen": ("Bratpfanne / Pfannen-Set", "CHF 20–50", "Beschichtete Aluminium­pfanne 26–28 cm — gut für den Alltag.", "CHF 50–150", "Gusseisen oder Edelstahl, auch beschichtet — z. B. Tefal, De Buyer.", "ab CHF 150", "Gusseisen (Le Creuset, Staub) oder Profi-Edelstahl — für die Ewigkeit."),
    "matratze": ("Matratze", "CHF 150–400", "Schaumstoff- oder Federkernatratze H2–H3 — gut für gelegentliche Nutzung.", "CHF 400–800", "Kaltschaum, Visco, 7 Zonen — z. B. Emma One, Casper — gute Allroundwahl.", "ab CHF 800", "Taschenfederkern + Komfortzone, Schweizer Qualität (Bico, Hüsler Nest) — langlebige Investition."),
    "soundbar-xxx": ("Soundbar Reserve", "CHF 80–200", "X", "CHF 200–600", "X", "ab CHF 600", "X"),
    "sessel": ("Sessel / Loungesessel", "CHF 100–300", "Einfacher Polstersessel — gut für Gästezimmer oder Lese­ecke.", "CHF 300–700", "Qualitäts-Stoff oder Ledersessel, ergonomisch — z. B. IKEA STRANDMON bis Mittelklasse.", "ab CHF 700", "Design-Sessel (Vitra, Hay, Moroso) — Investition für Wohnzimmer."),
    "kleiderschrank": ("Kleiderschrank / Garderobenschrank", "CHF 100–300", "Einfacher Schiebetür-Schrank, laminiert — gut für Gäste- oder Kinderzimmer.", "CHF 300–700", "Begehbarer Aufbauschrank (PAX-Klasse), Soft-Close — individuelle Planung.", "ab CHF 700", "Massivholz oder Schweizer Qualitätsschrank — langlebige Investition."),
    "teppich": ("Teppich / Wohnzimmer-Teppich", "CHF 30–100", "Polyester oder Jute, 140×200 cm — gut für Kinderzimmer und Küche.", "CHF 100–300", "Wolle oder Baumwolle, 160×230 cm, gute Qualität.", "ab CHF 300", "Hand­geknüpfter Teppich, Naturfaser-Premium oder Designer (Hay, Ferm Living)."),
    "ventilator": ("Ventilator / Deckenventilator", "CHF 20–60", "Tischventilator oder einfacher Stand-Ventilator — gut für ein Zimmer.", "CHF 60–150", "Turmventilator mit Timer und Fernbedienung — leiser und platzsparend.", "ab CHF 150", "Dyson Cool — keine Flügel, HEPA-Filter, Heizfunktion, sehr leise."),
    "router": ("Router / WLAN-Router", "CHF 30–80", "DSL/Kabelrouter mit Wi-Fi 5 — gut für Wohnungen bis 100 m².", "CHF 80–200", "Wi-Fi 6 (AX), Gigabit-LAN, Mesh-fähig — z. B. ASUS RT-AX86U, Fritzbox 7590.", "ab CHF 200", "Tri-Band Wi-Fi 6E oder Mesh-System (Eero Pro 6E, Netgear Orbi) — für grosse Häuser."),
    "milchaufschaeumer": ("Milchaufschäumer / Milchschäumer", "CHF 15–40", "Handmilchschäumer oder einfacher Induktions­schäumer — günstig und effektiv.", "CHF 40–100", "Elektrischer Milch­aufschäumer mit Heizoption — z. B. Nespresso Aeroccino.", "ab CHF 100", "Integriertes Milchsystem als Zusatz zur Espresso­maschine — bestes Ergebnis."),
    "raclette": ("Raclette-Grill / Raclette-Ofen", "CHF 30–60", "Raclette für 4 Personen, einfache Pfänchen — günstig und zuverlässig.", "CHF 60–130", "8 Personen, Tischgrill + Raclette, Stein­platte, gute Qualität.", "ab CHF 130", "STÖCKLI-Raclette (Schweizer Qualität) oder Steinofengrill — lang­lebige Investition."),
    "velo": ("Velo / Fahrrad", "CHF 300–600", "City-Velo oder Trekking­rad, 21–24 Gang — gut für Stadt­fahrten.", "CHF 600–1500", "Quali­täts-Trekkingrad oder MTB mit hydraulischen Bremsen.", "ab CHF 1500", "Carbon-Rennrad, Full-Suspension-MTB oder Gravel Bike (Trek, Scott, Specialized)."),
    "rudergeraet": ("Rudergerät / Rowing Machine", "CHF 200–500", "Magnet-Widerstand, Schienen­ruder — gut für Einsteiger.", "CHF 500–1500", "Luftwiderstand oder App-kompatibel (Ergatta, Hydrow) — für regelmässiges Training.", "ab CHF 1500", "Concept2 RowErg — Profi-Standard, Uni­versell, für Leistungs­sportler."),
    "zelt": ("Zelt / Campingzelt", "CHF 50–150", "2–3 Personen Kuppelzelt, wasserdicht 3000 mm — gut für Sommer­camping.", "CHF 150–400", "4 Personen Iglu oder Tunnel­zelt, wasserdicht 5000 mm, gute Belüftung.", "ab CHF 400", "3-Jahreszeiten-Trekkingzelt (MSR, Hilleberg) — leicht, sturmfest, für Touren­gänger."),
    "massagepistole": ("Massagepistole / Percussions-Massagegerät", "CHF 30–80", "Einfache Massage­pistole, 4–6 Aufsätze — gut für Muskelentspannung.", "CHF 80–200", "Theragun Mini, Hypervolt Go — leiser Motor, längere Akkulaufzeit.", "ab CHF 200", "Theragun Pro — professionelle Tiefengewebsmassage, App, 6 Aufsätze."),
    "inhalator": ("Inhalator / Vernebler", "CHF 20–50", "Druckluftvernebler für Nasen/Rachenbereich — gut für Erkältungen.", "CHF 50–120", "Membran-Vernebler, leise, schnell, für Asthma und Bronchitis.", "ab CHF 120", "Profi-Kompressor (PARI, Omron) — für regelmässige medizinische Inhalation."),
    "plattenspieler": ("Plattenspieler / Vinyl-Player", "CHF 80–200", "Audio-Technica AT-LP60X — Vollautomat, eingebauter Vorverstärker, Bluetooth.", "CHF 200–500", "Rega Planar 1, Pro-Ject Debut Carbon — manuelle Bedienung, hohe Klangqualität.", "ab CHF 500", "Rega P3, Pro-Ject X2 — audiophile Qualität, aus­wechselbare Tonabnehmer."),
    "vr-brille": ("VR-Brille / Virtual-Reality-Headset", "CHF 200–400", "Meta Quest 3S — Standalone, kein PC nötig, riesige Spielebibliothek.", "CHF 400–600", "Meta Quest 3 — Mixed Reality, 4K+, leicht.", "ab CHF 600", "Valve Index oder PlayStation VR2 — Profi-PC-VR mit Finger-Tracking."),
    "weinkuehlschrank": ("Weinkühlschrank / Weinklimaschrank", "CHF 80–200", "12–18 Flaschen, eine Temperatur­zone — gut für Rotwein-Lagerung.", "CHF 200–500", "2 Zonen (Rot+Weiss), 30–50 Flaschen, lautloser Kompressor.", "ab CHF 500", "Liebherr, Eurocave — 50+ Flaschen, präzise Temperatur, UV-Schutzglas."),
    "pool": ("Pool / Gartenpool", "CHF 50–200", "Aufblaspool oder einfacher Stahlwand­pool — für Kinder und kurzen Sommer­spass.", "CHF 200–800", "Oval-/Rundbecken 3×4 m, Filteranlage inklusive — z. B. Intex, Summer Fun.", "ab CHF 800", "Bestway oder fester Erdein­bau-Pool — langlebige Saisonautrüstung."),
    "sauna": ("Sauna / Heimsauna", "CHF 500–1500", "2-Personen-Infrarotkabine — einfache Montage, niedriger Strom­verbrauch.", "CHF 1500–4000", "4–6 Personen Holzsauna (Fichte/Hemlock), 6–9 kW-Ofen, inkl. Zubehör.", "ab CHF 4000", "Outdoor-Fasssauna oder Premium­kabine (Klafs, Tylö) — Schweizer Qualität, lange Lebensdauer."),
    "kettlebell": ("Kettlebell / Kurzhantel-Set", "CHF 20–60", "Einzelne Kettlebell 8–16 kg, beschichtet — für Grundübungen.", "CHF 60–150", "3er-Set 8/12/16 kg oder verstellbare Kurz­hantel — platzsparend.", "ab CHF 150", "Premium-Set (Rogue, Eleiko) oder verstellbare Kettlebell 8–32 kg."),
    "vakuumierer": ("Vakuumierer / Vakuum­sealer", "CHF 30–70", "Einstiegs-Balkenvakuumierer — gut für Lebensmittel­frisch­haltung.", "CHF 70–150", "Automatisch, inkl. Vakuum­beutel-Rolle, Marinieren-Funktion.", "ab CHF 150", "Kammer­vakuumierer (Sous-vide-tauglich) — für Profi-Küche und Lager­haltung."),
}
PRICE_DATA.update(_BATCH7)

# Batch 8
PRICE_DATA.update({
    "auto": ("Auto / Gebrauchtwagen", "CHF 5000–15000", "Zuverlässiger Gebrauchtwagen bis 5 Jahre alt — gut für Familien und Pendler.", "CHF 15000–35000", "Neuwagen Kompaktklasse oder gut erhaltener Mittelklasse-Gebrauchte.", "ab CHF 35000", "SUV, Premiumklasse (Mercedes, BMW, Volvo) oder Elektroauto (Tesla, Polestar)."),
    "heizluefter": ("Heizlüfter / Elektroheizung", "CHF 20–50", "1500–2000 W, einfache Thermostat-Steuerung — gut für kurzfristiges Heizen.", "CHF 50–150", "Infrarotheizung, Keramik-Heizlüfter mit Eco-Modus, App-Steuerung.", "ab CHF 150", "Konvektionsheizung (Dimplex) oder Infrarot-Panel für Dauerbetrieb."),
    "heizstrahler": ("Heizstrahler / Terrassenheizer", "CHF 50–120", "Elektrischer Heizstrahler 1500 W — gut für Balkon und kleine Terrasse.", "CHF 120–300", "Gas-Terrassenheizer, grössere Reichweite, 10 kW.", "ab CHF 300", "Carbon-Infrarot­heizer (Eurom, Burda) — sehr hoher Wirkungsgrad, wetterfest."),
    "schlafsack": ("Schlafsack / Deckenschlafsack", "CHF 30–80", "Kunstfaser, bis –5 °C — gut für Camping im Sommer.", "CHF 80–200", "Daunen oder Hohlkammerfaser, bis –10 °C, packbares Design.", "ab CHF 200", "Marmot, Western Mountaineering — bis –20 °C, ultraleicht, für Alpintouren."),
    "sommerreifen": ("Sommerreifen / Autoreifen", "CHF 50–90", "Gängige Marken in Standardgrösse — solide Basisausstattung.", "CHF 90–150", "Continental, Michelin, Pirelli — kurze Bremswege, hohe Laufleistung.", "ab CHF 150", "Ultra-High-Performance-Reifen (Michelin Pilot Sport) — für sportliches Fahren."),
    "winterreifen": ("Winterreifen / Ganzjahresreifen", "CHF 60–100", "Ganzjahresreifen oder Winterreifen Mittelklasse — solide für CH.", "CHF 100–160", "Continental, Michelin, Bridgestone Blizzak — beste Traktion auf Schnee.", "ab CHF 160", "Premium-Winterreifen für SUV und Sportwagen."),
    "koffer": ("Koffer / Trolley / Reisegepäck", "CHF 30–80", "Einfacher Hartschalen-Trolley 55 cm — gut für gelegentliche Reisen.", "CHF 80–200", "4-Rollen TSA-Schloss, leichtes Polycarbonat — Victorinox, Samsonite.", "ab CHF 200", "Rimowa Original, Tumi — Premium-Aluminium, Lebenszeit­garantie."),
    "gartenmoebel": ("Gartenmöbel / Outdoor-Möbel", "CHF 100–300", "Kunststoff-Set oder Alu-Klappstuhl + Tisch — günstig und praktisch.", "CHF 300–800", "Polyrattan-Set oder Aluminium, robust, wetterfest.", "ab CHF 800", "Teak-Holz oder Premium-Alu (Kettler, Gloster) — Schweizer Qualität."),
    "gartenliege": ("Gartenliege / Sonnenliege", "CHF 30–80", "Kunststoff oder einfache Alu-Liege — kompakt und günstig.", "CHF 80–200", "Polyrattan, Verstellmechanik, mit Auflagenpolster.", "ab CHF 200", "Premium-Alu oder Teak (Kettler, Fischer Möbel) — langlebig."),
    "trinkflaschen": ("Trinkflasche / Isolierflasche", "CHF 10–25", "Edelstahl oder BPA-freie Kunststoffflasche — zuverlässig und günstig.", "CHF 25–60", "Doppelwand-Vakuumisolation — z. B. Nalgene, Hydro Flask.", "ab CHF 60", "Klean Kanteen, S'well — Premium, Lebenszeit­garantie, nachhaltig."),
    "yoga-fitness": ("Yoga-Zubehör / Fitness-Matte", "CHF 15–40", "TPE oder PVC Fitnessmatte 6 mm — gut für Yoga und Pilates.", "CHF 40–80", "Naturgummi, anti-rutsch — Jade Harmony, Liforme.", "ab CHF 80", "Manduka PRO — 6 mm Gummi, sehr robust, 35-Jahres-Garantie."),
    "wellness-massage": ("Wellnessgeräte / Massage", "CHF 20–60", "Fussmassage­gerät oder einfaches Nackenmassage­kissen.", "CHF 60–150", "Shiatsu-Massagegerät mit Wärmefunktion, Massagepistole.", "ab CHF 150", "Profi-Massagestuhl (Beurer MG555) oder Infrarotsauna-Set."),
    "outdoor-camping": ("Camping-Ausrüstung", "CHF 50–150", "Einstiegs-Set: Schlafsack + Isomatte + Zelt.", "CHF 150–400", "Qualitäts-Zelt + Daunenschlafsack + Campingkocher.", "ab CHF 400", "Ultraleicht-Set (MSR, Big Agnes) — für Trekkingtouren in den Alpen."),
    "reise-zubehoer": ("Reise-Zubehör / Travel Accessories", "CHF 20–50", "Reisekissen, Augenbinde, Adapter-Set — Basis für die Reise.", "CHF 50–120", "Komfort-Reisekissen (Trtl, Cabeau), Premium-Adapter.", "ab CHF 120", "Smart-Reisesystem (Away, Horizn Studios) — Koffer mit Akku."),
    "sport": ("Sport-Equipment / Fitness", "CHF 20–80", "Grundausstattung: Springseil, Widerstandsbänder, Yogamatte.", "CHF 80–250", "Functional-Training-Set: Kettlebell, TRX, Box.", "ab CHF 250", "Profi-Heim-Gym: Stange, Scheiben, Hantelbank."),
    "mikrofon-podcast": ("Podcast-Mikrofon / USB-Mikrofon", "CHF 40–80", "USB-Kondensatormikrofon — gut für erste Podcast-Aufnahmen.", "CHF 80–200", "Shure MV7, Elgato Wave:3 — professionelle Klangqualität.", "ab CHF 200", "Shure SM7B + Interface — Broadcast-Standard."),
    "musikinstrument": ("Musikinstrument", "CHF 50–150", "Einstiegs-Instrument (Ukulele, Cajón, Mundharmonika).", "CHF 150–500", "Solide Gitarre, Keyboard 61 Tasten, Schlagzeug-Pad.", "ab CHF 500", "Profi-Instrument — langlebige Investition."),
    "lampen": ("Lampen / LED-Beleuchtung", "CHF 10–40", "Tischleuchte oder einfache Deckenlampe — günstig und funktional.", "CHF 40–120", "Dimmbare LED-Leuchte, Smart-Lamp (Philips Hue, IKEA Tradfri).", "ab CHF 120", "Design-Leuchte (Artemide, Flos) — Premium-Beleuchtung."),
    "koerperwaage": ("Körperwaage / Personenwaage", "CHF 15–40", "Einfache Digitalwaage, 0,1 kg Genauigkeit — gut für den Alltag.", "CHF 40–100", "Körperfett-Analyse, App-Sync (Withings, Garmin).", "ab CHF 100", "Withings Body Cardio — vollständige Körperzusammensetzung."),
    "munddusche": ("Munddusche / Oral-Irrigator", "CHF 20–50", "Einstiegs-Munddusche (Waterpik WP-100) — günstig und zuverlässig.", "CHF 50–120", "Portabel, wasserdicht, 5–7 Druckstufen.", "ab CHF 120", "Waterpik Ultra Plus — klinisch erprobt."),
    "ipl-geraet": ("IPL-Gerät / Haarentfernung", "CHF 60–150", "Einstiegs-IPL (Braun Silk-Expert 3) — für Beine und Achseln.", "CHF 150–300", "Braun Silk-Expert Pro 5, Philips Lumea.", "ab CHF 300", "Klinisches IPL-Heimgerät (Tria Laser 4X)."),
    "deko": ("Deko-Artikel / Wohnaccessoires", "CHF 15–50", "Vasen, Kerzenhalter, Bilderrahmen — dekorieren ohne grossen Aufwand.", "CHF 50–150", "Qualitäts­deko (HAY, ferm Living) — nachhaltiger Stil.", "ab CHF 150", "Objekte von Designer-Marken — zeitloser Wohnstil."),
    "sonnenschirm": ("Sonnenschirm / Gartenschirm", "CHF 30–80", "Einfacher 2-m-Schirm, UPF 40+ — gut für Balkon.", "CHF 80–200", "3 m Durchmesser, Kurbel, UV50+, wetterfest.", "ab CHF 200", "Ampelschirm oder Glatz Fortino — 360° drehbar, mit Beleuchtung."),
    "sonnenliege": ("Sonnenliege / Liegestuhl", "CHF 30–80", "Alu-Liegestuhl klappbar — günstig für Garten und Balkon.", "CHF 80–200", "Polyrattan mit Polster, verstellbare Rückenlehne.", "ab CHF 200", "Design-Sonnenliege (Dedon, Cane-line) — für Premium-Aussenbereich."),
    "sup": ("SUP / Stand-Up-Paddle", "CHF 200–400", "Aufblasbares Einsteiger-SUP 10'6'', gut für ruhige Gewässer.", "CHF 400–700", "All-Around oder Touring-SUP, bessere Gleitfähigkeit, stabileres Board.", "ab CHF 700", "Carbon- oder Glasfaser-SUP — leicht, schnell, für regelmässige Paddler."),
    "skiausruestung": ("Ski-Ausrüstung / Skier kaufen", "CHF 200–400", "Einstiegs-Allround-Ski, komplettes Leihset-Ersatz für Anfänger.", "CHF 400–900", "Intermediate-Carving-Ski mit Bindung — z. B. Rossignol, Salomon.", "ab CHF 900", "Expert-Ski (Stöckli, Atomic Redster) — für fortgeschrittene und Rennsportler."),
    "snowboard": ("Snowboard / Snowboard-Ausrüstung", "CHF 200–400", "Allround-Board, Bindung inklusive — gut für Einsteiger.", "CHF 400–800", "Park- oder Freeride-Board mit guter Flex, Profi-Bindung.", "ab CHF 800", "Premium-Board (Burton, Lib Tech) mit Profi-Boots und Bindung."),
    "uvp": ("Unterhaltungselektronik / Heimkino", "CHF 100–300", "Blu-ray-Player oder Streaming-Box (Apple TV 4K, Nvidia Shield).", "CHF 300–800", "Soundbar + Subwoofer oder Beamer Set.", "ab CHF 800", "Vollständiges Heimkino: Projektor + 5.1-Anlage + Leinwand."),
    "laubblaeser": ("Laubbläser / Akku-Laubbläser", "CHF 30–80", "Elektrischer Laubbläser, 600–800 W — gut für kleine Gärten.", "CHF 80–200", "Akku 18V+, Sauger-/Bläser-Funktion, z. B. Gardena, Bosch.", "ab CHF 200", "Benzin-Laubbläser oder Profi-Akku (Stihl BGA 200) — für grosse Flächen."),
    "kompressor": ("Kompressor / Druckluftkompressor", "CHF 50–150", "6–8 L, 1–1,5 kW — gut für Reifenfüllen, Nageln.", "CHF 150–400", "10–50 L, 2 kW, schnell wiederaufgeladen — für Heimwerken.", "ab CHF 400", "100+ L, 2,5 kW (Güde, Metabo) — für intensive Nutzung und Lackieren."),
    "fitnessgeraete": ("Fitnessgeräte / Heimtraining", "CHF 50–150", "Widerstandsbänder, Springseil, Balance-Board — platzsparend.", "CHF 150–500", "Rudergerat, Crosstrainer oder Heimtrainer Einstieg.", "ab CHF 500", "Profi-Gerät (Concept2, NordicTrack) — Clubqualität für zu Hause."),
    "fitnesstracker": ("Fitness-Tracker / Activity-Tracker", "CHF 30–80", "Einfaches Aktivitäts-Band mit Schrittzähler und Schlaf-Monitor.", "CHF 80–200", "GPS, Herzfrequenz, SpO2, Garmin Vivofit oder Fitbit Charge.", "ab CHF 200", "Vollwertige GPS-Smartwatch (Garmin Forerunner 955) für Triathleten."),
})

if __name__ == "__main__":
    main()
